### ISSUE TITLE
readline close not emitted if input is stdin

### ISSUE THREAD

**Issue by belak** [joyent/node#5307] opened 2013-04-16 07:15 UTC
I've been working with node.js a little and I'm trying to read some config values in through stdin on program start. This is what I came up with:

https://gist.github.com/anonymous/5392981

However, when running like the following, it only outputs "end", not "closed"
```
echo hello | node test.js
```

Adding terminal: false fixes it, but according to the docs this shouldn't be the case.
https://gist.github.com/gluxon/5393130

The docs say that any time input's "end" is triggered, readline's "close" should be.

Is this just something I'm missing, or is this an actual issue?

**Comment by jasnell** [comment] 2015-05-26 19:36
Unable to reproduce in v0.12 using the provided test case. Closing. Can reopen if new information is received.

**Closed by jasnell** 2015-05-26 19:36 UTC

**Comment by belak** [comment] 2015-05-27 07:26
This does appear to work now. Thanks for the follow up!
