### ISSUE TITLE
dgram: No way to detect if a port is in use when binding

### ISSUE THREAD

**Issue by jamesatfanduel** [joyent/node#5425] opened 2013-05-07 22:31 UTC
There is currently no way to request or detect if a port is already in use when binding a UDP socket.

One solution would be to have a modified bind, or an optional parameter to force `SO_REUSEADDR` to false during a bind (and the potential to supply a failure callback for more graceful handling).

Currently, running two instances of:

```js
var socket = dgram.createSocket('udp4');
socket.bind(9364, function() {

    socket.on('message', function(data, origin) {
        console.log('Received:', data, 'from', origin);
    });

    var msg = new Buffer('test');
    socket.send(msg, 0, msg.length, 'localhost', 9364);
});
```

Demonstrates that both *appear* to succeed, but only the first running instance will receive unicast messages - since there is no way to know whether you are the first, second, or nth bind to that port - so there is no way to write a server to receive unicast UDP messages, and *know* with absolute certainty that it will, in fact, receive them when they are sent to that port.

This makes writing any resilient server process pretty much impossible - there is no way to elegantly step off and retry (if a service has been restarted and the port is in the process of being freed), or report an error if the service cannot be bound in a useful manner.

**Comment by jasnell** [comment] 2015-06-30 01:23
Testing on v0.12 and io.js this has been resolved. It's still potentially an issue for v0.10 but given how old the issue is, it's not likely worth backporting. Closing. Can reopen if necessary.

**Closed by jasnell** 2015-06-30 01:23 UTC
Labels: dgram, feature-request

**Comment by hit9** [comment] 2015-08-28 19:24
Hi, what should I do to enable REUSEPORT with my udp socket now? seems via method addMembership ?
