### ISSUE TITLE
benchmark net-connect fails

### ISSUE THREAD

**Issue by trevnorris** [joyent/node#5319] opened 2013-04-17 18:19 UTC
The following occurs on v0.10.x and master.

Output of running the test for substantial time:
```
$ /usr/bin/time ./node benchmark/tls/tls-connect.js concurrency=1 dur=120

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: This socket is closed.
    at Socket._write (net.js:618:19)
    at doWrite (_stream_writable.js:211:10)
    at writeOrBuffer (_stream_writable.js:201:5)
    at Socket.Writable.write (_stream_writable.js:172:11)
    at Socket.write (net.js:596:40)
    at write (_stream_readable.js:557:24)
    at flow (_stream_readable.js:566:7)
    at _stream_readable.js:534:7
    at process._tickCallback (node.js:415:13)
Command exited with non-zero status 8
47.08user 2.61system 0:49.81elapsed 99%CPU (0avgtext+0avgdata 115836maxresident)k
```
I've posted the output of debug mode v8 stack trace, along with much gdb backtrace info, at https://gist.github.com/trevnorris/5406502

/cc @indutny @bnoordhuis

**Comment by jasnell** [comment] 2015-05-26 19:33
Unable to reproduce. Closing. @trevnorris feel free to reopen if you're still experiencing issues.

**Closed by jasnell** 2015-05-26 19:33 UTC
Labels: tls
