### ISSUE TITLE
mongodb error

### ISSUE THREAD

**Issue by nguye381** [joyent/node#9134] opened 2015-02-03 22:47 UTC
Hello, 

I installed mongodb (64-bit Linux ver 2.6.7).  I installed mongodb driver of node.js v0.10.26 via "npm install mongodb". 

However, I got an error ("Failed to load c++ bson extension, using pure JS version
... ") when executing the below line of code:

var mongo = require('mongodb').MongoClient;

Any suggestion(s) to fix the problem?

Thanks,

**Comment by misterdjules** [comment] 2015-02-04 01:33
I wasn't able to reproduce this with node v0.10.36.

Anyway, it doesn't seem to be an issue with node's core, and it looks like it's an issue with your current setup, so I will close the issue in this bug tracker.

Could you please post this question either on StackOverflow or in [the Node.js Google group](https://groups.google.com/forum/#!forum/nodejs) (don't forget to paste the _whole output_ of the commands you're running)? I'll be happy to help you over there.

Thank you!

**Closed by misterdjules** 2015-02-04 01:33 UTC

**Comment by nguye381** [comment] 2015-02-04 13:57
Hi ?Julien,


I currently use Node v0.10.26...., so I will try newer version of Node v0.10.36.

I will post the issue again in the Node.js Google group as you suggested (this

seems to be a better place to bring up issues or ask general questions since I

am brand new to Node) if I still run into the problem.


Thanks much for your response,

Regards, >>Thoai

________________________________
