### ISSUE TITLE
Debug option and express extremely slow to load - debugging unusable

### ISSUE THREAD

**Issue by askhogan** [joyent/node#9177] opened 2015-02-10 07:27 UTC
I switched to .12 expecting speed gains, but what I have found is that my development workflow is not workable.  Each restart is taking 5-10 minutes.  On .10 it was slow, but maybe 20 seconds.

**Comment by askhogan** [comment] 2015-02-10 07:30
#9125

**Comment by misterdjules** [comment] 2015-03-25 19:34
Thank you for reporting this issue @askhogan :+1: , closing as a duplicate of #9125.

**Closed by misterdjules** 2015-03-25 19:34 UTC
