### ISSUE TITLE
Failed test: simple/test-debugger-client

### ISSUE THREAD

**Issue by jbergstroem** [joyent/node#4926] opened 2013-03-05 22:07 UTC
I'm getting a reproducible bug for test-debugger-client (Linux g2-x86_64 3.8.0-gentoo SMP Mon Feb 25 10:24:34 EST 2013 x86_64 QEMU Virtual CPU version 0.14.1 GenuineIntel GNU/Linux):
```bash
node -v && node test/simple/test-debugger-client
v0.9.11
got stderr data "debugger listening on port 13683\n"
>>> connecting...

events.js:69
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: connect ECONNREFUSED
    at errnoException (net.js:840:11)
    at Object.afterConnect [as oncomplete] (net.js:831:19)
```

...nothing specific passed to `./configure` (defaults)

**Comment by jasnell** [comment] 2015-05-20 18:19
Given that original reporter indicated inability to reproduce the problem any longer, and there's been zero activity on this for two years and since it's working in the master, closing. Can reopen if necessary.

**Closed by jasnell** 2015-05-20 18:19 UTC
