### ISSUE TITLE
v0.10.34: w/o OpenSSL build error

### ISSUE THREAD

**Issue by joerg-krause** [joyent/node#8896] opened 2014-12-18 08:16 UTC
This issue was already reported for v0.10.33 (https://github.com/joyent/node/issues/8676), but unfortunatly didn't made it in the bug fix release.

Patch is prepared as PR (https://github.com/joyent/node/pull/8761) which works for for Buildroot (http://git.buildroot.net/buildroot/tree/package/nodejs/nodejs-0004-fix-build-error-without-OpenSSL-support.patch)

**Comment by misterdjules** [comment] 2015-06-12 00:42
Closing as a duplicate of #8676, thank you for reporting it!

**Closed by misterdjules** 2015-06-12 00:42 UTC
