### ISSUE TITLE
Crypto: Stream interface is not padded

### ISSUE THREAD

**Issue by buschtoens** [joyent/node#5570] opened 2013-05-27 14:30 UTC
When using the stream interface for `crypto.Cipher` and `crypto.Decipher` `.setAutoPadding(true)` does not have any effect. This is understandable, as padding every `read` event would extremely bloat up the resulting code.

However, when the source stream closes, `crypto` fails with `TypeError: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length`, indicating, that the final block could not be encoded, as it does not meet the block length. When using auto padding, the (De-)Cipher object should automatically pad the last `read` event.

Sample code provoking the error:
```js
var net = require("net")
  , crypto = require("crypto");

var credentials = { algorithm: "aes192", password: "password" }
  , decipher = crypto.createDecipher(credentials.algorithm, credentials.password)
  , cipher = crypto.createCipher(credentials.algorithm, credentials.password);

decipher.setAutoPadding(true);
cipher.setAutoPadding(true);

net.createServer(function(socket) {
  socket.pipe(socket);
}).listen(2000);

var socket = net.connect(2000);

socket.pipe(decipher).pipe(process.stdout);
process.stdin.pipe(cipher).pipe(socket); 

cipher.write("Too short.");
cipher.end();
```

[StackOverflow](http://stackoverflow.com/questions/16775219/how-to-deal-with-block-length-in-node-js-crypto-streams)

**Comment by jasnell** [comment] 2015-05-26 22:27
Unable to reproduce the error. Closing. Can reopen if necessary

**Closed by jasnell** 2015-05-26 22:27 UTC
