### ISSUE TITLE
socket.remoteAddress in undefined when connecting using nmap

### ISSUE THREAD

**Issue by wildchild** [joyent/node#16523] opened 2015-04-18 12:27 UTC
I pointed nmap to opened socket in node. Can anyone shed a light, why remoteAddress is undefined? In what case it's possible and how to prevent such behaviour? Tried on osx and linux.
```js
var net = require('net');

var server = net.createServer(function (socket) {
  console.log(socket.remoteAddress);
});
server.listen(12345, '127.0.0.1');
```
output: <code>undefined</code>

<code>nmap 127.0.0.1 -p 12345</code>

node versions: 0.10.38 and 0.12.2

**Comment by misterdjules** [comment] 2015-04-24 00:47
Thank you @wildchild for reporting this issue. As you already mentioned, this is a duplicate of https://github.com/joyent/node/issues/7566. Closing it as such.

**Closed by misterdjules** 2015-04-24 00:47 UTC
