### ISSUE TITLE
Error stack becomes empty in node v0.12 stable

### ISSUE THREAD

**Issue by tinganho** [joyent/node#9253] opened 2015-02-20 03:37 UTC
node v0.12 just broke several of my applications. I rely on a function that gets a caller's filename. Though that function doesn't work anymore in node v0.12.

Here is a faling test repo:
https://github.com/tinganho/get-caller

**Comment by jasnell** [comment] 2015-02-20 17:17
In general, the approach you're taking here seems rather odd. There are better ways of getting the caller's filename. If you're not running in strict mode, you can use `arguments.callee.caller` to get the caller rather than hacking through the stack trace. You can use `__dirname` and `__filename` as well. (see http://stackoverflow.com/questions/3133243/how-to-get-path-to-current-script-with-node-js)

**Comment by tinganho** [comment] 2015-02-20 17:32
@jasnell `__dirname` and `__filename` is not the same it only give you current dir and current file?  `arguments.callee.caller` don't get you the filename. 

I want the file where a function is called.

**Comment by meandmycode** [comment] 2015-02-20 17:51
What is the error you get?

**Comment by cjihrig** [comment] 2015-02-20 19:28
Sounds like this is likely a duplicate of #5478. If so, it's a v8 change, and is out of our control. If this is not the same issue, we can reopen this.

**Closed by cjihrig** 2015-02-20 19:28 UTC

**Comment by meandmycode** [comment] 2015-02-20 20:31
Whilst I think this is the hackiest thing that nbody should be doing, the change that has happened seems to be that the CallSite objects returned in the stack are no longer populated with properties.

But if you are desperate to shoot yourself in the foot then calling ```.toString()``` on them will return a string of the following format:

_functionname_ (_path_:_row_:_column_)

But non of this functionality seems to be well defined so your best course of action is to not do this.
