### ISSUE TITLE
use strict - util.inspect - showHidden:true - TypeError: Illegal access to a strict mode caller function

### ISSUE THREAD

**Issue by quicktoolbox** [joyent/node#9035] opened 2015-01-15 12:50 UTC
When using "showHidden:true", errors encountered on 'repl' and 'util' modules.
I have checked every module, and global... only 2 error.

'use strict';
// works
console.log(util.inspect(util,{showHidden:false,depth:null,colors:true}));  
// fails
console.log(util.inspect(util,{showHidden:true,depth:null,colors:true}));  

util.js:355
  desc = Object.getOwnPropertyDescriptor(value, key) || { value: value[key] };
                ^
TypeError: Illegal access to a strict mode caller function.
    at Function.getOwnPropertyDescriptor (native)
    at formatProperty (util.js:355:17)
    at util.js:294:14
    at Array.map (native)
    at formatValue (util.js:293:19)
    at formatProperty (util.js:373:15)
    at util.js:294:14
    at Array.map (native)
    at formatValue (util.js:293:19)
    at Object.inspect (util.js:140:10)

**Comment by cjihrig** [comment] 2015-01-19 02:32
I'm sorry, I don't think I completely understand your issue. On the 0.12 branch, the following code does not throw an exception for `util` or `repl`.

```javascript
'use strict';
var util = require('util');

console.log(util.inspect(util, {
  showHidden: false,
  depth: null,
  colors: true
}));

console.log(util.inspect(util, {
  showHidden: true,
  depth: null,
  colors: true
}));
```

What exact code are you running, and on which version of Node?

**Comment by misterdjules** [comment] 2015-06-02 17:16
Closing because the current information available does not allow us to reproduce the problem, and the original reporter did not provide any additional info.

**Closed by misterdjules** 2015-06-02 17:16 UTC
