### ISSUE TITLE
EADDRNOTAVAIL after many http.requests

### ISSUE THREAD

**Issue by jochenonline** [joyent/node#6833] opened 2014-01-09 07:18 UTC
This code breaks with `EADDRNOTAVAIL`  with `i` between `20000` and `30000`. A webserver (i.e. Apache) must be availabe on `localhost:80`.

When broken:

* one **cannot do** a `http.request` from node.js (any process) to `localhost` for (round about) 10 seconds.
* while these 10 seconds
    * one **can do**  a `http.request` with any other program to `localhost` (i.e. `curl http://localhost`)
    * one **can do** a `http.request` from node.js to any other domain.

This is the code:

```javascript
var http = require( "http");

function httpRequest( callback ) {
  var options = {
    host: 'localhost',
    port: 80,
    path: ''
  },
  data = "";

  http.get(options, function(resp){
    resp.on('data', function( chunk ){   
      data += chunk;
    }).on("end", function() {
      callback( null, data );
    });
  }).on("error", function(e){
    callback( e );
  });
}

function loop( i, callback ) {
  if( i < 100000 ) {
    httpRequest( function( err, data ) {
      if( err ) {
        console.log( "Error!", i, err );
        return;
      }
      if( i % 1000 === 0 ) {
        console.log( i );
      }
      loop( i+1, callback );
    });
  } else {
    callback();
  }
}

console.log( "GO!");
loop( 0, function() {
  console.log( "READY!");
});
```

One can avoid the error by disabling the `globalAgent` with

```javascript
var options = {
  host: 'localhost',
  port: 80,
  path: '',
  agent: false // <-- this 
},
data = "";
```

but I think that the loop should run without error also with the default `globalAgent`, shouln't it!? So there seems to be a problem with the socket pooling.

**Comment by ravi** [comment] 2015-03-24 00:32
Looks like yet another manifestation of #4769...

**Comment by jasnell** [comment] 2015-05-28 22:10
It does appear to be a duplicate of #4769. Closing in favor of that one. Can reopen if it turns out to not actually be a duplicate.

**Closed by jasnell** 2015-05-28 22:11 UTC
