### ISSUE TITLE
Intl: Build "English-only" binaries for the distribution.

### ISSUE THREAD

**Issue by srl295** [joyent/node#7676] opened 2014-05-23 05:35 UTC
A new issue to continue the discussion in #6371 and #4689  - especially to implement https://github.com/joyent/node/issues/6371#issuecomment-42491824 

* provide a way to build against any ICU, not just Chromium's
* default build has very little data (just English) for a small file size
* default disk location at build time for additional data `--with-default-icu-path=...`
* runtime option `--icu-data-dir=`path.. or NODE_ICU_DATA env var can override the default 
* ICU won't be in github, but can be enabled by default in builds.

/cc @tjfontaine @trevnorris

**Comment by srl295** [comment] 2015-01-05 23:54
- [ ] TODO:  [Document how to update node's timezone data](srl295/node/#9)

**Comment by misterdjules** [comment] 2015-01-06 01:11
I find that having this "general discussion" issue makes it difficult to track the current state of this work. 

If I understand correctly, here's what we want regarding the distribution of binaries that include ICU support:
* First, release binaries with "small" ICU support, the target for that is the 0.11.15 milestone. This is already supported, only Jenkins jobs must be updated to use `--with-intl=small-icu` and `vcbuild.bat small-icu`.
* When https://github.com/joyent/node/issues/8983 is implemented, include "full" ICU data in binary distributions (Windows and OS X installers, as well as binary tarball). This can be done in a later milestone, like 0.12.1, because it doesn't change node's API.

If we agree on that, I suggest closing this issue and creating two separate issues that correspond to the two points mentioned above.

@tjfontaine @srl295 @trevnorris What do you think?

**Comment by srl295** [comment] 2015-01-06 05:57
> First, release binaries with "small" ICU support, the target for that is
the 0.11.15 milestone. This is already supported, only Jenkins jobs must be
updated to use --with-intl=small-icu and vcbuild.bat small-icu.

But, that's the only and entire point of #7676 - if that's true,, it should
be considered fixed.

**Comment by misterdjules** [comment] 2015-01-07 00:59
@srl295 Ok, I was just confused by some comments [that mention several sub-issues/sub-tasks](https://github.com/joyent/node/issues/7676#issuecomment-64704230) that we may want to address separately. This issue also contains [comments that were not updated](https://github.com/joyent/node/issues/7676#issuecomment-63399139) and I think that just adds to the confusion.

Like I said I would rather have each issue/PR address only "atomic" issues so that we can track them more easily.

I just tested the `small-icu` build on all supported platforms here: http://jenkins.nodejs.org/job/nodejs-julien/235/ and here: http://jenkins.nodejs.org/job/nodejs-julien-windows/77/, and there is no regression. The failing test on Windows has nothing to do with ICU-related changes. It was introduced by b636ba8 and is already tracked by https://github.com/joyent/node/issues/8986.

However, in [my previous comment](https://github.com/joyent/node/issues/7676#issuecomment-68811475) I failed to mention that some more work needs to be done to have `small-icu` support enabled for some binary packages (OSX pkg and binary tarballs). Basically, the base `Makefile` needs to be updated to pass `with-intl=small-icu` to the `configure` script. I will take care of that.

So as soon as the changes needed to make binary packages include small-icu land, I suggest closing this issue and we'll start creating several more specific issues. @srl295 How does that sound?

**Comment by srl295** [comment] 2015-01-07 04:17
Sounds good to me... more later.

**Comment by misterdjules** [comment] 2015-01-08 05:37
@srl295 I just submitted https://github.com/joyent/node/pull/8994 that enables small-icu support for all binary packages.

**Comment by misterdjules** [comment] 2015-01-15 01:50
#8994 Landed in 67f87a743dee4951374dd240c25e31cd507e6c5f, so closing this issue. @srl295 Please ping me on #libuv when you have some time to discuss the next steps.

Thanks all!

**Closed by misterdjules** 2015-01-15 01:50 UTC
Labels: i18n, v0.12
