### ISSUE TITLE
Node.js Http server socket "Hangup" error

### ISSUE THREAD

**Issue by keithjia** [joyent/node#6639] opened 2013-12-05 18:09 UTC
Node.js Http server will throw a socket handup error when receiving a "Get" request with a request body. As a server, shouldn't it ignore the request body like other implementation of Http Servers? 

Repro verion: 0.10.20

example code for sending request with a "body":
```javascript
var http = require("http");

var body = {
    "data" : "my data"
};

var options = {
    hostname: 'localhost',
    port: 8100,
    path: '/shared/storage?key=shared/echo',
    method: 'GET',

    headers : {
        "Content-Type" : "application/json",
        'Content-Length': Buffer.byteLength(JSON.stringify(body))
    }
};

var req = http.request(options, function(res) {
    console.log('STATUS: ' + res.statusCode);
    console.log('HEADERS: ' + JSON.stringify(res.headers));
    res.setEncoding('utf8');
    res.on('data', function (chunk) {
        console.log('BODY: ' + chunk);
    });
    res.on('end', function (chunk) {
        console.log('response: ENDED');
    });
});

req.on('error', function(e) {
    console.log('problem with request: ' + e.message);
});

// write data to request body
req.write(JSON.stringify(body));

req.end();
```

**Comment by jasnell** [comment] 2015-05-28 21:40
request payloads with HTTP GET are undefined and the spec allows servers to reject them. Closing this as it's technically not a bug. There are other existing issues that discuss whether or not we should add request payloads as a feature

**Closed by jasnell** 2015-05-28 21:40 UTC
Labels: http
