### ISSUE TITLE
Free RAM continuously decreases slowly while piping a lot of files

### ISSUE THREAD

**Issue by steebchen** [joyent/node#9360] opened 2015-03-09 16:12 UTC
I'm using the request module to pipe large files to users. The code is not special:
`request.get("http://foo.bar/file").pipe(res);`
I'm running this script on Ubuntu v12.04 and the script randomly crashes, cancelling all downloads. 
The error message:
> Out of memory: Kill process 9342 (nodejs) score 793 or sacrifice child
> Killed process 9342 (nodejs) total-vm:1333552kB, anon-rss:410648kB, file-rss:0kB

The problem can't be within the request module because some days ago I tried it with the http module but it resulted in the same error.
I'm using v0.10.33 and my server has 500MB RAM.

----------------------
EDIT:
It seems that the problem doesn't occurr on a server with 4GB RAM.  So maybe 500MB are just not enough for piping large files.

-------------------------
EDIT 2:
I tried the same with the built-in modules, but it resulted in the same error:

    http.get(url, function (response) {
        res.writeHead(response.statusCode, response.headers);
        response.pipe(res);
    });

**Comment by Freyert** [comment] 2015-03-12 13:45
What was the size of the file?

**Comment by steebchen** [comment] 2015-03-12 15:14
The size of the files depend, but most time 200-600MB. I recently tried it on a server with 4GB RAM and it seems that this problem doesn't occurr there...

**Comment by Freyert** [comment] 2015-03-12 22:28
@steebchen my best guess is that the pipe is filling up on that data and never flushing it to the other end. The server with 4GB probably has plenty of RAM to fully load the file onto the pipe and then flush it. Ideally on your 500MB server you'd call a `flush` function every few MB to clear them out of memory and send them onward so more bytes can fill the pipe. I'm not sure how to do this in Node, but I'll help you look.

**Comment by misterdjules** [comment] 2015-03-13 00:23
@steebchen How often does that happen, and under what conditions does it happen (how many concurrent users and after how much time, etc.)?

Also, do you have some code that doesn't use any external dependency (just Node.js' built-in modules) that reproduces this issue?

**Comment by steebchen** [comment] 2015-03-15 15:03
I found out that the problem occurrs on a 6GB VPS too. The server doesn't crash, but I can clearly see that it eats RAM (and the RAM doesn't get flushed or something like that). 3 days ago, about 5 of 6GB were used. 2 days ago, 4.7, yesterday 3.6 and today 3.2GB. Does somebody know how to achieve that?

**Comment by steebchen** [comment] 2015-03-28 12:15
I tried the same with a stream, and it has the same issue. When I stream a 500MB file, the RAM continuously decreases, the swap RAM will be used and after another 500MB file the server crashes because it is out of RAM. Do I have to (or can I) manually delete the data object or flush/clear the RAM somehow?

    stream.on("data", function (data) {
        res.write(data);
        // Do I have to delete 'data' somehow?
    });
    
    stream.on("end", function () {
        res.end();
    });

**Comment by jasnell** [comment] 2015-06-25 20:51
Closing as duplicate of https://github.com/joyent/node/issues/14189. We can reopen if it truly is a separate issue.

**Closed by jasnell** 2015-06-25 20:51 UTC
Labels: http, streams
