### ISSUE TITLE
http.get({ agent: false }) response truncated

### ISSUE THREAD

**Issue by Bonuspunkt** [joyent/node#4145] opened 2012-10-15 19:39 UTC
i am piping an couchdb view though my nodejs server and the response is sometimes truncated
```javascript
// proxy @ server
var http = require('http');

http.createServer(function(req, res) {
        http.get({
                port: 5984,
                path: '/irc/_design/base/_view/base',
                agent: false
        }, function(cliRes) {
                res.writeHead(cliRes.statusCode, cliRes.headers);
                cliRes.pipe(res);
        });
}).listen(process.argv[2] || 8888);
```

```javascript
// multiGet.js
var http = require('http');

http.globalAgent.maxSockets = 100;

for (var i = 0; i < 10; i++) {
    http.get({
        host: 'server',
        port: 8888
    }, function(res) {
        var length = 0;
        res.on('data', function(chunk) { length += chunk.length; });
        res.on('end', function() { console.log(length)});
    });
}
```

```
~/ $ node mulitGet.js 
1620230 // <-- this is the correct size
1620230
1613528
1620230
1620230
1612065
1620230
1595345
1620230
1606522
```
this behaviour is only reproduce able, if i run `multiGet.js` from a different host then the server, removing the `agent: false` also solves the problem

**Comment by JoshuaGross** [comment] 2015-04-07 20:40
@jayproulx Did you end up digging into this more? I'm seeing this a lot today, having a hard time figuring out where the issue is.

**Comment by jayproulx** [comment] 2015-04-07 20:56
@JoshuaGross Nope, I just delayed a little to get around the issue.

**Comment by jasnell** [comment] 2015-05-19 19:43
@JoshuaGross ... are you able to provide a simple test case that reliably demonstrates the problem?

**Comment by JoshuaGross** [comment] 2015-05-19 19:59
@jasnell I was able to reproduce it very reliably against some internal servers at Yahoo, but never against any public APIs that I tested against. Thus, in my case, I'm pretty sure it was an intermittent issue with specific endpoints I was using, as I wasn't able to reproduce it against properly-written endpoints.

**Comment by jasnell** [comment] 2015-05-20 17:03
Ok, for now then I'm inclined to close the issue. I have not been able to recreate the issue myself using v0.10, v0.12 or io.js. We can reopen if more information is received or if the problem manifests anywhere else.

**Closed by jasnell** 2015-05-20 17:03 UTC
Labels: http, maybe-close
