### ISSUE TITLE
Node.js REPL hangs http requests on v0.12

### ISSUE THREAD

**Issue by feyzo** [joyent/node#9420] opened 2015-03-16 23:31 UTC
I found a problem with REPL on Node.js v12.0. It wasn't sending some of the http requests on time.

- Reproduced on OSX 10.10.2
- Didn't reproduce on openSUSE, Windows 7, Ubuntu 14.04

Here is the minimal reproducible example with documentation: https://github.com/feyzo/repl-hang-reduced-case
Also stackoverflow post: http://stackoverflow.com/questions/29076314/node-js-repl-hangs-http-requests

Problems:
1. http requests ran with repl interface hangs.
2. Running multiple repl requests after a failed one, hanged http requests stops hanging and reaches to server.

**Comment by jasnell** [comment] 2015-03-18 22:32
Hmm.. Unable to replicate on 10.10.1. Planning to update to 10.10.2 tonight so will try it again.

**Comment by feyzo** [comment] 2015-03-19 12:15
I started testing different versions after your comment @jasnell, it looks like problem started with 11.12 release. 

Result breakdown:
✓: Working
-: Not tested
✖: Failing
- v0.11.0   ✓
- v0.11.1   -
- v0.11.2   -
- v0.11.3   -
- v0.11.4   -
- v0.11.5   -
- v0.11.6   -
- v0.11.7   -
- v0.11.8   -
- v0.11.9   -
- v0.11.10  ✓
- v0.11.11  ✓
- v0.11.12  ✖
- v0.11.13  ✖
- v0.11.14  -
- v0.11.15  -
- v0.11.16  ✖
- v0.12.0   ✖

**Comment by feyzo** [comment] 2015-03-20 11:48
### Git bisect result

First bad and installable commit:
e2fcfea46e334743aed24993eeebb2482c6ea762

Had to skip these commits because `make` command was failing. Probably because these changes requires other set of commits to work:
d2f2a32b897840d91cf240830ad5cf5f0e33a0c8
e92d35d80be6e193cb547e94c6fbf3654542dbaa

hey, authors @tjfontaine @saghul

**Comment by jasnell** [comment] 2015-03-20 13:23
Hmm.. Oddly I'm still unable to replicate the issue. Let me play around
with it a bit more on a few different platforms to see what results I get.

**Comment by feyzo** [comment] 2015-03-20 13:30
@jasnell  I was able to reproduce it on OSX 10.10.2 with two different machines.

Didn't reproduce on openSUSE, Windows 7, Ubuntu 14.04

**Comment by sixmen** [comment] 2015-04-05 00:42
I think this is the same issue as #9310

**Comment by misterdjules** [comment] 2015-06-09 00:29
Confirmed that this issue is a duplicate of #9310, and that it's fixed by https://github.com/joyent/node/pull/25475.

**Closed by misterdjules** 2015-06-09 00:29 UTC
