### ISSUE TITLE
Child_process spawn execute "svn add * --force" command error

### ISSUE THREAD

**Issue by qiangyee** [joyent/node#9042] opened 2015-01-16 10:47 UTC
There had two kinds of results when I  use child_process spawn('svn',  ['add', '*' ,'--force']) and exec('svn add * --force') function. The spawn gives me error, but exec execute OK. 
Here is my code:
spawn.test.js
```javascript
var spawn = require('child_process').spawn;
var err = '';
var cmd = spawn('svn', ['add', '*', '--force'], {
  cwd: 'path/'  // this path is exists and a svn local copy 
});
cmd.on('close', function(code, signal){
   console.log(err); 
  // print: 
  //svn: warning: W155010: 'path/*' not found
  //svn: E200009: Could not add all targets because some targets don't exist
  //svn: E200009: Illegal target for the requested operation
});
cmd.stderr.on('data', function(chunk){
  err += chunk.toString();
});
```
exec.test.js
```javascript
var exec = require('child_process').exec;
exec('svn add * --force', {
  cwd: 'path/'
},function (error, stdout, stderr) {
  console.log(stderr); // print nothing!
});
```

more info:
```
$ node -v 
v0.10.25
$ uname -a
Darwin xxx 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64
$ svn --version
svn, version 1.7.17 (r1591372)
   compiled Sep 18 2014, 13:06:44
```

**Comment by misterdjules** [comment] 2015-01-16 17:33
`*` is interpreted by the shell as a globbing pattern, and is substituted by a list of strings that correspond to filenames that match this pattern.

Contrary to `child_process.exec`, `child_process.spawn` doesn't use the shell to run programs and thus cannot interpret these patterns.

Closing as a duplicate of #8935.

**Closed by misterdjules** 2015-01-16 17:33 UTC
