### ISSUE TITLE
Updating NPM Fails On Windows (Related to Windows Instaler)

### ISSUE THREAD

**Issue by Meligy** [joyent/node#4554] opened 2013-01-10 04:24 UTC
When you update NPM in Windows, it updates the user-specific app-data packages folder. 

However, Node installs NPM into Program Files and adds the bin folder to the PATH. This version in Program Files is not possible to update in any way.

The installer also adds the user-specific folder to the PATH, but it adds it AFTER the Program Files folder, so, after updating NPM, calling NPM again matches the version in Program Files still.

More details:
http://gurustop.net/blog/2012/11/26/nodejs-npm-update-g-not-working-in-windows-solution-workaround-node-modules/

**Comment by jasnell** [comment] 2015-05-18 17:43
@orangemocha ... is this still an issue?

**Comment by orangemocha** [comment] 2015-06-16 11:34
Yes, this is still an issue, but a duplicate of https://github.com/joyent/node/issues/8528. Closing this one in favor of https://github.com/joyent/node/issues/8528.

**Closed by orangemocha** 2015-06-16 11:34 UTC
Labels: maybe-close, npm, windows
