### ISSUE TITLE
npm broken on Mavericks OS X in 0.10..35

### ISSUE THREAD

**Issue by numinasthmatic** [joyent/node#8952] opened 2014-12-30 01:37 UTC
The installer, at least when installing over 0.10.33, gives the following result when executing nom install:
lydia:~/Library/CalibreBooks 11:04:25$ npm install ws

node.js:838
    var cwd = process.cwd();
                      ^
Error: ENOENT, no such file or directory
    at Function.startup.resolveArgv0 (node.js:838:23)
    at startup (node.js:58:13)
    at node.js:929:3
lydia:~/Library/CalibreBooks 11:07:59$ npm --help

node.js:838
    var cwd = process.cwd();
                      ^
Error: ENOENT, no such file or directory
    at Function.startup.resolveArgv0 (node.js:838:23)
    at startup (node.js:58:13)
    at node.js:929:3

I created the following file as /usr/local/bin/npm, based on /usr/local/lib/node_modules/npm/bin/npm.

#!/bin/sh

basedir=`dirname "$0"`
basedir=`dirname "$basedir"`

node "$basedir/lib/node_modules/npm/bin/npm-cli.js" "$@"

When I ran this as
$ npm install ws
the install worked.

Subsequently, restoring the original /usr/local/bin/npm link to npm-cli.js perform the same install command correctly.  I don't know whether this was because the 'ws' install fled were already in place.

**Comment by misterdjules** [comment] 2015-01-06 01:16
I couldn't reproduce this issue on Mavericks.

It seems that the current working does not exist when `npm` runs. Are you sure that `~/Library/CalibreBooks` exists at the time npm runs? It is possible that somehow it had been deleted after changing the current directory to it.

**Comment by numinasthmatic** [comment] 2015-01-06 01:55
Yes, ~/Library/CalibreBooks is a long-standing directory.  As I said, after the first failure, it worked, so I can give you no further information.

**Comment by pierrerigal** [comment] 2015-01-06 08:07
Same problem here with an other directory. The problem is bash cannot find the working directory. 

Restart terminal and that's it.

**Comment by misterdjules** [comment] 2015-01-06 17:55
I'm not sure I understand properly what the original issue reported by @numinasthmatic is. @pierrerigal Were you able to reproduce it? If so, how?

**Comment by numinasthmatic** [comment] 2015-01-07 02:10
I assumed that
$ npm install ws
would install in a standard location.  Is this true?  On that assumption, I issued the command in the directory where I happened to be.  ~/Library/CalibreBooks is not a link, but an actual directory, so no confusion should arise there.  Having issued that command, I go the result mentioned.  I then tried
$ npm --help

Same story.

I created a shell file that basically did the same thing that the original link (from /usr/local/bin/npm) was doing, and executed it.  Having done that, the restored original link also worked without any problems.

I can't work it out either.  The 'cwd' should only be invoked within the script after cd from the original working directory from which the command is executed.  That original directory should be completely irrelevant.  Are there any circumstances under which that does not occur?

**Comment by pierrerigal** [comment] 2015-01-07 08:42
@misterdjules  No I can't :( . If I start a new project everything goes well.
In my case, it was just after a clean install of Yosemite, I launched terminal, clone my repo, install and run composer, then install npm (for grunt mainly). The first launch gave me the error reported by @numinasthmatic, my folder was not symlinked and really existed so I assumed it was a $PATH problem that was not correctly set after the whole installation so I simply restarted Terminal.app et voilà :)

**Comment by jasnell** [comment] 2015-08-29 19:04
Unable to reproduce. Appears to be a local issue. Closing

**Closed by jasnell** 2015-08-29 19:04 UTC
Labels: npm

**Comment by vcarl** [comment] 2015-10-02 06:07
Wanted to chime in, I ran into this on Mavericks as well, @pierrerigal was right in my case. Was using fish instead of bash, but restarting the shell solved it.

**Comment by JeremyMiller** [comment] 2016-01-05 16:53
This issue seems to be related to Grunt, as it occurs after running a grunt task (for me).

Opening a new terminal window fixes the problem, so Grunt must be messing with some environment variables or something.

**Comment by ghost** [comment] 2016-01-05 18:39
Disregard what I said in my previous (deleted) comment, I finally figured it out. My Grunt script was deleting and recreating the folder that my terminal was in, which is what causes this error.

I don't know if anything can/should be done about this.
