### ISSUE TITLE
"FATAL ERROR: Allocation failed - process out of memory"

### ISSUE THREAD

**Issue by borisovg** [joyent/node#9114] opened 2015-01-29 13:47 UTC
## Summary:

I'm writing a TCP server in Node that accepts data line by line. As I was testing it with increasingly longer lines I managed to reliably crash node due to memory usage if I convert the incoming buffer to a string and then parse it one character at a time. Changing the code to parse the buffer instead resolves the issue.

The test file I am using is 66MB of text, all on one line (68266668 characters + new line) :-)

Working directly with the buffer is obviously faster, but I don't see where the memory leak could be coming from.

Node version is 0.10.32, running on Debian (Sid).

## Code:

Server 1 (this crashes, with Node process memory climbing to about 1.5GB).

````javascript
/*jshint node:true*/
'use strict';

var net = require('net');

var server = net.createServer(function (socket) {
        var data = '';

        socket.on('data', function (buffer) {
                var c, i, s = buffer.toString('utf-8');

                for (i = 0; i < s.length; i += 1) {
                        c = s.charAt(i);

                        if (c === '\n' && data) {
                                console.log('Line length: ' + data.length + ' characters');
                                data = '';
                        
                        } else {
                                data += c;
                        }
                }
        });

        socket.on('end', function () {
                console.log('Connection closed');
        });
});

server.listen(31234);
````

Server 2 (this does not crash and memory remains constant at ~100MB)

````javascript
/*jshint node:true*/
'use strict';

var net = require('net');

var server = net.createServer(function (socket) {
        var data = '';

        socket.on('data', function (buffer) {
                var i, start = 0;

                for (i = 0; i < buffer.length; i += 1) {
                        if (buffer[i] === 10) {
                                data += buffer.slice(start, i).toString('utf-8');
                                console.log('Line length: ' + data.length + ' characters');
                                data = '';
                                start = i + 1;
                        }
                }

                if (start < buffer.length) {
                        data += buffer.slice(start).toString('utf-8');
                }
        });

        socket.on('end', function () {
                console.log('Connection closed');
        });
});

server.listen(31234);
````

The data file was generated with:

````bash
echo $(dd if=/dev/urandom bs=1024 count=50000 2>/dev/null | base64 -w 0) > data.txt
````

And the test client I am using is:

````bash
#!/bin/bash

set -o errexit
set -o nounset

shopt -s execfail

# open socket
FD=$(date +%s%N)
exec {FD}<>/dev/tcp/localhost/31234

# send data
cat $1 >&$FD

# close socket
exec {FD}>&-
````

## Output:

Client is run as "./client.sh data.txt"

Server 1 returns:

````
FATAL ERROR: JS Allocation failed - process out of memory
Aborted
````

Server 2 returns:

````
Line length: 68266668 characters
Connection closed
````

**Comment by piscisaureus** [comment] 2015-01-29 23:27
Reduced test case:

```js
var buf = new Buffer(1024*1024*100);
buf.fill(42);
var s = buf.toString();
var s2 = '';
for (var i = 0; i < s.length; i++)
  s2 += s.charAt(i);
```

Agreed it seems a little odd.

**Comment by piscisaureus** [comment] 2015-01-29 23:28
@erikcorry Is this expected?

**Comment by erikcorry** [comment] 2015-01-30 07:06
This is expected.  You are building a 100 million character string,1
character at a time.  That builds a chain with 100m elements, each being an
object of 32 or 40 bytes.

Instead of using + on a string, push the characters on an array, then use
join at the end. That will only use about a gigabyte.

Or you can periodically flatten the string with s.test(/./), but that will
take quadratic time for large strings.

**Comment by stevemind** [comment] 2015-02-10 11:20
Bonjour,

J'ai des problèmes avec 1&1 sur mes Wordpress :

http://www.aubeuf-hacquin-yoann.fr/
http://www.stevemindmagicien.fr/
http://www.evenements-animations-artistiques.fr/

voici l 'erreur :
Fatal error: Out of memory (allocated 82051072) (tried to allocate 32 bytes) in 

Pouvez vous m'aider à optimiser mes wordpress avec le php.ini + techniques ?

**Comment by revolunet** [comment] 2015-02-10 11:46
@stevemind: il faut contacter le support 1&1 c'est pas ici.
et le mieux est encore de ne PAS utiliser 1&1 qui est l'hébergeur le plus moisi que je connaisse. OVH/gandi are much better.

**Comment by trevnorris** [comment] 2015-02-11 20:18
@erikcorry Awesome tip w/ `s.test(/./);` :)

**Comment by trevnorris** [comment] 2015-02-11 20:19
Okay, so closing this as Woks As Intended.

**Closed by trevnorris** 2015-02-11 20:19 UTC
