### ISSUE TITLE
segmentation fault cause by use of `new String(x)`

### ISSUE THREAD

**Issue by Gozala** [joyent/node#6691] opened 2013-12-12 21:18 UTC
I have being observing some segmentation faults on v0.10.21 / 22 in a small compiler
I wrote that runs on node. Same code has no issues when running in chrome or firefox.

I discovered that change in my code that introduced this bug was related to use of `new String(token)` to box strings (I started creating string instances for string tokens
in order to attach metadata on them). Segmentation fault happens not at the creation
of these objects though but later during manipulation. Also I can't yet create simple reproducible test case as even small changes seem to affect behavior (for example if I add some `console.log` statements segmentation fault no longer happens.

It also seems that short strings (like "--" "nil") tend to be a cause, although it maybe combination of other things too.

**Comment by jasnell** [comment] 2015-05-28 21:49
@Gozala ... I know it's been a while, but is this still an issue for you?

**Comment by jasnell** [comment] 2015-06-03 17:07
@Gozala ... going to close this issue for now because (a) there's been no further information and (b) there's no reliable way of reproducing the problem. If you're continuing to see issues on this, comment here and we can reopen if necessary.

**Closed by jasnell** 2015-06-03 17:07 UTC

**Comment by Gozala** [comment] 2015-06-03 17:15
@jasnell sorry for the late response, I have worked around the issue on my side & have not really had a chance to dig into finding a version of code where I was running into.

I'll comment back once I'll have a reproducible test case.

Thanks
