### ISSUE TITLE
Cluster module can lose track of connections if child processes die

### ISSUE THREAD

**Issue by msmithrdio** [joyent/node#7006] opened 2014-01-30 22:31 UTC
Our application uses the cluster module, and periodically we kill worker processes - the master re-spawns them, and new connections can go to the new workers.

We're now trying to run 0.11.10, and occasionally, a connection is 'lost' - it's in limbo, not disconnected, nor processed by a child.

I believe this happens in the following scenario:
 - Master accepts a connection
 - Master passes new connection to worker with sendmsg
 - Before worker can recvmsg to get the passed file descriptor...
 - Worker process is terminated
 - Master process leaves the socket open

I will attach a simple minimized test script that reproduces this problem for me (it works fine in 0.10.x).

**Comment by jasnell** [comment] 2015-05-28 22:30
@cjihrig @msmithrdio ... is this still an issue? Do we need to backport anything to v0.10?

**Comment by rdio-reviewboard** [comment] 2015-05-28 22:42
Unsure if this is an issue on recent 0.12 (I haven't tried updating/removing our workarounds) - but this was a regression in 0.11, so backporting to 0.10 is definitely not required.

**Comment by jasnell** [comment] 2015-05-28 22:46
I'm unable to reproduce in v0.12 or io.js so going to close this for now then. Can reopen if new information is received.

**Closed by jasnell** 2015-05-28 22:46 UTC
Labels: cluster, master
