### ISSUE TITLE
msi database records

### ISSUE THREAD

**Issue by Bartatcompany** [joyent/node#8987] opened 2015-01-07 15:09 UTC
When installing a new version unattended the installer leaves the old version record in the msi database.
So you get multiple records visible in programs and features. for example  node.js version 0.10.33, node.js version 0.10.35. When doing centralized software updates this is troublesome if you would like to "run this msi where currently node.js with a version of xyz is installed" the msi installer should replace the msi database record for the replaced version.

**Comment by joaocgreis** [comment] 2015-07-07 09:09
I could not reproduce on Windows 7 64bit, the old version is correctly removed.

@Bartatcompany Is this still an issue for you? Can you share the installation logs?

**Comment by Bartatcompany** [comment] 2015-07-08 07:33
Hi João,

Will do a mass deploy of the most recent version 0.12.6 today to all developer stations.
I will let you know the results in a day or two.

Thanks,
Bart van den Bosch

**Comment by Bartatcompany** [comment] 2015-07-09 14:49
Hi João,

I can confirm this problem does not exist anymore within the 0.12.6 release.
If I recall correctly I found the problem with a 0.10.* release.

I think it’s safe to close this ticket.

Thanks,
Bart van den Bosch

**Comment by joaocgreis** [comment] 2015-07-10 09:00
@Bartatcompany Good to know! Closing for now, if you see this again we can reopen the issue and investigate more.

**Closed by joaocgreis** 2015-07-10 09:00 UTC
Labels: installer, windows
