### ISSUE TITLE
Installation failed: node-v0.10.13-x64.msi 

### ISSUE THREAD

**Issue by Spetnik** [joyent/node#5849] opened 2013-07-14 12:25 UTC
When installign node-v0.10.13-x64.msi on my Windows 7 64bit machine, it fails with the message "node.js setup wizard ended prematurely". This is the install log: http://pastebin.com/NYT18xkA

Any help would be greatly appreciated.

Thanks
Aaron

**Comment by jasnell** [comment] 2015-05-26 21:22
Appears to no longer be an issue. Can reopen if new information is presented.

**Comment by JimF42** [comment] 2015-05-27 00:07
I just downloaded node-v0.12.4-x64.msi and can confirm that this is indeed **still an issue**, albeit a slight different error message is presented, but it is still the same problem that I posted above on 1/6/2014.

The messages now are:
* MSI (s) (D4:68) [16:36:54:599]: Executing op: ActionStart(Name=CreateFolders,Description=Creating folders,Template=Folder: [1])
* MSI (s) (D4:68) [16:36:54:599]: Executing op: FolderCreate(Folder=\\ad.local\system\users\\[myAcctName]\Start Menu\Programs\Node.js\,Foreign=0,SecurityDescriptor=BinaryData,)
* Info 1926.Could not set file security for file '\\ad.local\system\users\\[myAcctName]\Start Menu\Programs\Node.js\'. Error: 0.  Verify that you have sufficient privileges to modify the security permissions for this file.
* MSI (s) (D4:68) [16:36:54:654]: Error in rollback skipped.	Return: 3

If you like, I can get you the entire log file. Also, due to the nature of the error (at least in my case) I understand that this is not easily recreated by most developers as you need an environment where your user documents (normally located at C:\Users\\[myAcctName] is relocated to a network server. See https://technet.microsoft.com/en-us/library/cc732275.aspx for details.

I do not know if I am allowed to reopen this issue myself, so if I can't, then the owner may need to.

**Comment by jasnell** [comment] 2015-05-27 00:26
hmm... @orangemocha ... thoughts?

**Comment by JimF42** [comment] 2015-05-27 12:42
Hey @jasnell, @orangemocha, I think I have a clue. I looked at the file properties of your msi to see if I could determine what "brand" it was (appears to be Microsoft's installer toolkit) to see if I could search for the issue via the installer docs.

I didn't get quite that far since I found [this forum post](https://social.msdn.microsoft.com/Forums/windows/en-US/215a5e8a-e58b-45ef-b9fb-c07209b911cc/windows-installer-cannot-successfully-install-application-if-appdata-folder-is-redirected?forum=winformssetup) that probably gives the correct answer regardless of which installer you are using. 

In short, some installers give the option of asking the user if they want to install for "Just for me" (not escalated) or for "Everyone" (definitely escalated). If you are installing for "Everyone", wouldn't it make sense to put the shortcut for the Start Menu under the "All Users" Start Menu instead of the current user's? The All Users Start Menu would never be redirected by Folder Redirection, only the logged in user gets redirected.

If you really **want** to install to the current user's Start Menu, the accepted answer points to [another web page](https://msdn.microsoft.com/en-us/library/aa370905(v=vs.85).aspx#system_folder_properties) which may give you a clue as to how that is done. Since I don't use the Windows Installer, so I will have to leave the details of how either way that is actually done to you folks...

If you tweak the install package, feel free to post a comment back on the forum of where I can find a new MSI and I will be happy to try it out for you.

**Comment by orangemocha** [comment] 2015-05-27 13:23
@JimF42 , thanks for the detailed report.

>I think the difference is that when you double-click on an MSI and it escalates, it runs as TrustedInstaller and while that account has access to everything on my box, it does not have network access. When I run an escalated command prompt, it is running as me, but already escalated (the MSI never needs to ask for escalation), so it works.

This sounds like a plausible explanation. I need to do a bit of research to determine the best practice in this case. 

In the meantime, can you please share the entire log file?

**Comment by JimF42** [comment] 2015-05-27 13:53
@orangemocha, How would I get you the log file? The file is +11MB and I can't seem to attach a file to this post in github.

As far as determining the best practice, that sounds great, but keep in mind even for users where the installation does not error out, I still think (in hindsight) the installation is not correct. You are installing the software for "Everyone", but only installing the start menu item "Just for me" (the current user). I bet if you log on to your own computer as a different user you will find that there is no start menu item for jsnode. Mind you, I say all of this without testing it myself... :smirk:

**Comment by orangemocha** [comment] 2015-05-27 14:01
@JimF42  can you upload the log file to a cloud storage service (eg DropBox, OneDrive, etc) and post the link here?

**Comment by JimF42** [comment] 2015-05-27 14:28
@orangemocha you can find the log files at [Dropbox](https://www.dropbox.com/s/brekdov0wco2i3n/Nodejs.logs.zip?dl=0). As an added bonus I also sent you the log file from the failed 10.24 install from January. It may not be of any interest or use to you--do whatever you wish with that one...

Each one is designated with the program version in the file name.

**Comment by joaocgreis** [comment] 2015-07-22 16:00
Fixed by 8e80528453aca0354422162e09c7c9f4700ddb1e. Thank you!

**Closed by joaocgreis** 2015-07-22 16:00 UTC
Labels: installer, P-1, windows

**Comment by JimF42** [comment] 2015-07-22 16:16
Would you like me to retest the install in my environment? If so, let me know where I can get the MSI?

**Comment by orangemocha** [comment] 2015-07-22 17:43
@JimF42 if you want to test an unsigned version of the MSI, here it is: https://www.dropbox.com/s/g2rb5mkjhw5rtb7/node-v0.12.7-x86.msi?dl=0

You'll need to uninstall any prior installation of node, because the fix only works on fresh installs.

**Comment by JimF42** [comment] 2015-07-22 18:36
Yes, I can confirm that this package installs just fine with no special intervention in my environment.

Thanks!

**Comment by orangemocha** [comment] 2015-07-22 22:36
Great to know, thank you @JimF42 ! 

Removing the link...

**Comment by orangemocha** [comment] 2015-07-22 23:26
The fix will be included in the 0.12.8 release.

**Comment by hnhegde** [comment] 2016-06-27 17:45
Hello,
I see this issue is closed. But am trying to install nodejs on Windows 10 64 bit. Fails with 1603. Please see message extract below. Complete log file attached. Appreciate solutions. Tried most of the ones already mentioned above. None worked. 

[nodejs-install-admin_log.txt](https://github.com/nodejs/node-v0.x-archive/files/335491/nodejs-install-admin_log.txt)

`MSI (s) (50:A4) [19:34:10:839]: Running installation inside multi-package transaction D:\Downloads\node-v4.4.6-x64.msi
MSI (s) (50:A4) [19:34:10:839]: Grabbed execution mutex.
MSI (s) (50:A8) [19:34:10:843]: MainEngineThread is returning 1603
MSI (s) (50:A4) [19:34:10:850]: User policy value 'DisableRollback' is 0
MSI (s) (50:A4) [19:34:10:850]: Machine policy value 'DisableRollback' is 0
MSI (s) (50:A4) [19:34:10:850]: Incrementing counter to disable shutdown. Counter after increment: 0
MSI (s) (50:A4) [19:34:10:850]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (50:A4) [19:34:10:852]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (50:A4) [19:34:10:852]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
MSI (c) (20:D0) [19:34:10:856]: Back from server. Return value: 1603
MSI (c) (20:D0) [19:34:10:856]: Decrementing counter to disable shutdown. If counter >= 0, shutdown will be denied.  Counter after decrement: -1
MSI (c) (20:D0) [19:34:10:856]: PROPERTY CHANGE: Deleting SECONDSEQUENCE property. Its current value is '1'.
Action ended 19:34:10: ExecuteAction. Return value 3.
MSI (c) (20:D0) [19:34:10:857]: Doing action: FatalError
MSI (c) (20:D0) [19:34:10:857]: Note: 1: 2205 2:  3: ActionText 
Action start 19:34:10: FatalError.
Action ended 19:34:11: FatalError. Return value 2.
Action ended 19:34:11: INSTALL. Return value 3.
MSI (c) (20:D0) [19:34:11:842]: Destroying RemoteAPI object.
MSI (c) (20:58) [19:34:11:842]: Custom Action Manager thread ending.
=== Logging stopped: 27-Jun-16  19:34:11 ===
MSI (c) (20:D0) [19:34:11:849]: Note: 1: 1708 
MSI (c) (20:D0) [19:34:11:849]: Product: Node.js -- Installation failed.

MSI (c) (20:D0) [19:34:11:853]: Windows Installer installed the product. Product Name: Node.js. Product Version: 4.4.6. Product Language: 1033. Manufacturer: Node.js Foundation. Installation success or error status: 1603.

MSI (c) (20:D0) [19:34:11:857]: Grabbed execution mutex.
MSI (c) (20:D0) [19:34:11:857]: Cleaning up uninstalled install packages, if any exist
MSI (c) (20:D0) [19:34:11:858]: MainEngineThread is returning 1603
=== Verbose logging stopped: 27-Jun-16  19:34:11 ===
`

**Comment by MylesBorins** [comment] 2016-06-27 17:48
@hnhegde can you please open a new issue over at https://github.com/nodejs/node/issues

This issue tracker is deprecated
