### ISSUE TITLE
Issue installing node js in Mac OS - Mavericks 

### ISSUE THREAD

**Issue by stellamiranda** [joyent/node#7894] opened 2014-07-03 20:50 UTC
I cloned the repo doing 

git clone git://github.com/ry/node.git

then, moved to node folder with 

cd node 

when I run make command

make 

I got this error 

/Applications/Xcode.app/Contents/Developer/usr/bin/make -C out BUILDTYPE=Release V=1
Makefile:280: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:278: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:282: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:280: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:284: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:282: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:286: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:284: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:288: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:286: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:290: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:288: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:292: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:290: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:296: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:292: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:298: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:296: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:300: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:298: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:302: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:300: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:304: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:302: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:306: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:304: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:308: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:306: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:310: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:308: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:313: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:310: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:315: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:313: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:317: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:315: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:319: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:317: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:321: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:319: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:323: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:321: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:325: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:323: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:327: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:325: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:332: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:327: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:334: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:332: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:336: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:334: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:338: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:336: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:340: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:338: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:342: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:340: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:344: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:342: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:346: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:344: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:350: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:346: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:352: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:350: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:354: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:352: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:356: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:354: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:358: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:356: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:360: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:358: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:362: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:360: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:364: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:362: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:367: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:364: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:369: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:367: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:371: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:369: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:373: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:371: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:375: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:373: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:377: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:375: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:379: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:377: warning: ignoring old commands for target `/Users/stella/apps/Mi'
Makefile:381: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:379: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/cares/cares.target.mk:154: warning: overriding commands for target `/Users/stella/apps/Mi'
Makefile:381: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/cares/cares.target.mk:159: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/cares/cares.target.mk:154: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/cares/cares.target.mk:162: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/cares/cares.target.mk:159: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/cares/cares.target.mk:187: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/cares/cares.target.mk:162: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/http_parser/http_parser.target.mk:97: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/cares/cares.target.mk:187: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/http_parser/http_parser.target.mk:102: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/http_parser/http_parser.target.mk:97: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/http_parser/http_parser.target.mk:105: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/http_parser/http_parser.target.mk:102: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/http_parser/http_parser.target.mk:130: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/http_parser/http_parser.target.mk:105: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/http_parser/http_parser_strict.target.mk:97: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/http_parser/http_parser.target.mk:130: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/http_parser/http_parser_strict.target.mk:102: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/http_parser/http_parser_strict.target.mk:97: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/http_parser/http_parser_strict.target.mk:105: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/http_parser/http_parser_strict.target.mk:102: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/http_parser/http_parser_strict.target.mk:130: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/http_parser/http_parser_strict.target.mk:105: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/http_parser/test-nonstrict.target.mk:100: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/http_parser/http_parser_strict.target.mk:130: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/http_parser/test-nonstrict.target.mk:105: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/http_parser/test-nonstrict.target.mk:100: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/http_parser/test-nonstrict.target.mk:108: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/http_parser/test-nonstrict.target.mk:105: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/http_parser/test-nonstrict.target.mk:138: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/http_parser/test-nonstrict.target.mk:108: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/http_parser/test-strict.target.mk:100: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/http_parser/test-nonstrict.target.mk:138: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/http_parser/test-strict.target.mk:105: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/http_parser/test-strict.target.mk:100: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/http_parser/test-strict.target.mk:108: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/http_parser/test-strict.target.mk:105: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/http_parser/test-strict.target.mk:138: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/http_parser/test-strict.target.mk:108: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/openssl/openssl-cli.target.mk:179: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/http_parser/test-strict.target.mk:138: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/openssl/openssl-cli.target.mk:184: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/openssl/openssl-cli.target.mk:179: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/openssl/openssl-cli.target.mk:187: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/openssl/openssl-cli.target.mk:184: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/openssl/openssl-cli.target.mk:217: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/openssl/openssl-cli.target.mk:187: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/openssl/openssl.target.mk:826: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/openssl/openssl-cli.target.mk:217: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/openssl/openssl.target.mk:829: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/openssl/openssl.target.mk:826: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/openssl/openssl.target.mk:834: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/openssl/openssl.target.mk:829: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/openssl/openssl.target.mk:837: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/openssl/openssl.target.mk:834: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/openssl/openssl.target.mk:840: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/openssl/openssl.target.mk:837: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/openssl/openssl.target.mk:843: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/openssl/openssl.target.mk:840: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/openssl/openssl.target.mk:868: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/openssl/openssl.target.mk:843: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/uv/libuv.target.mk:136: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/openssl/openssl.target.mk:868: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/uv/libuv.target.mk:141: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/uv/libuv.target.mk:136: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/uv/libuv.target.mk:144: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/uv/libuv.target.mk:141: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/uv/libuv.target.mk:169: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/uv/libuv.target.mk:144: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/uv/run-benchmarks.target.mk:124: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/uv/libuv.target.mk:169: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/uv/run-benchmarks.target.mk:129: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/uv/run-benchmarks.target.mk:124: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/uv/run-benchmarks.target.mk:132: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/uv/run-benchmarks.target.mk:129: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/uv/run-benchmarks.target.mk:163: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/uv/run-benchmarks.target.mk:132: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/uv/run-tests.target.mk:207: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/uv/run-benchmarks.target.mk:163: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/uv/run-tests.target.mk:212: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/uv/run-tests.target.mk:207: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/uv/run-tests.target.mk:215: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/uv/run-tests.target.mk:212: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/uv/run-tests.target.mk:246: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/uv/run-tests.target.mk:215: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/uv/uv_dtrace_header.target.mk:21: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/uv/run-tests.target.mk:246: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/uv/uv_dtrace_header.target.mk:36: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/uv/uv_dtrace_header.target.mk:21: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/uv/uv_dtrace_provider.target.mk:8: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/uv/uv_dtrace_header.target.mk:36: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/generate_trig_table.host.mk:21: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/uv/uv_dtrace_provider.target.mk:8: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/generate_trig_table.host.mk:36: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/generate_trig_table.host.mk:21: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/js2c.host.mk:21: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/generate_trig_table.host.mk:36: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/js2c.host.mk:42: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/js2c.host.mk:21: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/js2c.host.mk:57: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/js2c.host.mk:42: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/mksnapshot.x64.host.mk:109: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/js2c.host.mk:57: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/mksnapshot.x64.host.mk:114: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/mksnapshot.x64.host.mk:109: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/mksnapshot.x64.host.mk:117: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/mksnapshot.x64.host.mk:114: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/mksnapshot.x64.host.mk:147: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/mksnapshot.x64.host.mk:117: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/postmortem-metadata.target.mk:21: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/mksnapshot.x64.host.mk:147: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/postmortem-metadata.target.mk:36: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/postmortem-metadata.target.mk:21: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8.host.mk:8: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/postmortem-metadata.target.mk:36: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8.target.mk:8: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8.host.mk:8: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_base.x64.host.mk:280: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8.target.mk:8: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_base.x64.host.mk:285: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_base.x64.host.mk:280: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_base.x64.host.mk:288: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_base.x64.host.mk:285: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_base.x64.host.mk:313: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_base.x64.host.mk:288: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_base.x64.target.mk:280: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_base.x64.host.mk:313: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_base.x64.target.mk:285: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_base.x64.target.mk:280: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_base.x64.target.mk:288: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_base.x64.target.mk:285: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_base.x64.target.mk:313: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_base.x64.target.mk:288: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_libbase.x64.host.mk:98: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_base.x64.target.mk:313: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_libbase.x64.target.mk:98: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_libbase.x64.host.mk:98: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_nosnapshot.x64.host.mk:112: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_libbase.x64.target.mk:98: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_nosnapshot.x64.host.mk:117: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_nosnapshot.x64.host.mk:112: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_nosnapshot.x64.host.mk:120: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_nosnapshot.x64.host.mk:117: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_nosnapshot.x64.host.mk:145: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_nosnapshot.x64.host.mk:120: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_nosnapshot.x64.target.mk:112: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_nosnapshot.x64.host.mk:145: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_nosnapshot.x64.target.mk:117: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_nosnapshot.x64.target.mk:112: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_nosnapshot.x64.target.mk:120: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_nosnapshot.x64.target.mk:117: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_nosnapshot.x64.target.mk:145: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_nosnapshot.x64.target.mk:120: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_snapshot.host.mk:26: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_nosnapshot.x64.target.mk:145: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_snapshot.host.mk:142: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_snapshot.host.mk:26: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_snapshot.host.mk:147: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_snapshot.host.mk:142: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_snapshot.host.mk:150: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_snapshot.host.mk:147: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_snapshot.host.mk:181: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_snapshot.host.mk:150: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_snapshot.target.mk:26: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_snapshot.host.mk:181: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_snapshot.target.mk:142: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_snapshot.target.mk:26: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_snapshot.target.mk:147: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_snapshot.target.mk:142: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_snapshot.target.mk:150: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_snapshot.target.mk:147: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_snapshot.target.mk:181: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_snapshot.target.mk:150: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/zlib/zlib.target.mk:110: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/v8/tools/gyp/v8_snapshot.target.mk:181: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/zlib/zlib.target.mk:115: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/zlib/zlib.target.mk:110: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/zlib/zlib.target.mk:118: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/zlib/zlib.target.mk:115: warning: ignoring old commands for target `/Users/stella/apps/Mi'
deps/zlib/zlib.target.mk:143: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/zlib/zlib.target.mk:118: warning: ignoring old commands for target `/Users/stella/apps/Mi'
node.target.mk:170: warning: overriding commands for target `/Users/stella/apps/Mi'
deps/zlib/zlib.target.mk:143: warning: ignoring old commands for target `/Users/stella/apps/Mi'
node.target.mk:175: warning: overriding commands for target `/Users/stella/apps/Mi'
node.target.mk:170: warning: ignoring old commands for target `/Users/stella/apps/Mi'
node.target.mk:178: warning: overriding commands for target `/Users/stella/apps/Mi'
node.target.mk:175: warning: ignoring old commands for target `/Users/stella/apps/Mi'
node.target.mk:209: warning: overriding commands for target `/Users/stella/apps/Mi'
node.target.mk:178: warning: ignoring old commands for target `/Users/stella/apps/Mi'
node_dtrace_header.target.mk:21: warning: overriding commands for target `/Users/stella/apps/Mi'
node.target.mk:209: warning: ignoring old commands for target `/Users/stella/apps/Mi'
node_dtrace_header.target.mk:36: warning: overriding commands for target `/Users/stella/apps/Mi'
node_dtrace_header.target.mk:21: warning: ignoring old commands for target `/Users/stella/apps/Mi'
node_dtrace_provider.target.mk:8: warning: overriding commands for target `/Users/stella/apps/Mi'
node_dtrace_header.target.mk:36: warning: ignoring old commands for target `/Users/stella/apps/Mi'
node_dtrace_ustack.target.mk:8: warning: overriding commands for target `/Users/stella/apps/Mi'
node_dtrace_provider.target.mk:8: warning: ignoring old commands for target `/Users/stella/apps/Mi'
node_etw.target.mk:8: warning: overriding commands for target `/Users/stella/apps/Mi'
node_dtrace_ustack.target.mk:8: warning: ignoring old commands for target `/Users/stella/apps/Mi'
node_js2c.host.mk:21: warning: overriding commands for target `/Users/stella/apps/Mi'
node_etw.target.mk:8: warning: ignoring old commands for target `/Users/stella/apps/Mi'
node_js2c.host.mk:36: warning: overriding commands for target `/Users/stella/apps/Mi'
node_js2c.host.mk:21: warning: ignoring old commands for target `/Users/stella/apps/Mi'
node_mdb.target.mk:8: warning: overriding commands for target `/Users/stella/apps/Mi'
node_js2c.host.mk:36: warning: ignoring old commands for target `/Users/stella/apps/Mi'
node_perfctr.target.mk:8: warning: overriding commands for target `/Users/stella/apps/Mi'
node_mdb.target.mk:8: warning: ignoring old commands for target `/Users/stella/apps/Mi'
specialize_node_d.target.mk:21: warning: overriding commands for target `/Users/stella/apps/Mi'
node_perfctr.target.mk:8: warning: ignoring old commands for target `/Users/stella/apps/Mi'
specialize_node_d.target.mk:36: warning: overriding commands for target `/Users/stella/apps/Mi'
specialize_node_d.target.mk:21: warning: ignoring old commands for target `/Users/stella/apps/Mi'
make[1]: *** No rule to make target `../%.c', needed by `/Users/stella/apps/Mi'.  Stop.
make: *** [node] Error 2

**Comment by jasnell** [comment] 2015-06-03 18:30
Unable to reproduce. Closing. Can reopen if necessary

**Closed by jasnell** 2015-06-03 18:30 UTC
