### ISSUE TITLE
assert.deepEqual has bad test

### ISSUE THREAD

**Issue by othiym23** [joyent/node#4523] opened 2013-01-06 00:31 UTC
If you look at https://github.com/joyent/node/blob/master/lib/assert.js#L208-L209

```javascript
  // an identical 'prototype' property.
  if (a.prototype !== b.prototype) return false;
```

is incorrect. `a` and `b` are instances, not constructor functions, and as such, will never have prototypes set directly on them. Similar deep equality tests do the following instead:

```javascript
  // a and b are on the same constructor chain
  if (a.constructor !== b.constructor) return false;
```

`objEquiv` should probably be changed similarly, although a case could be made that this test could be junked, seeing as how this hasn't been noticed until now.

**Comment by jokeyrhyme** [comment] 2015-03-03 22:39
I just noticed that this does NOT throw:
```javascript
assert.deepEqual(Object.create({tea:'chai'}), Object.create({tea:'black'}))
```

Weird.

**Comment by cjihrig** [comment] 2015-03-04 01:53
This is a shortcoming of `assert.deepEqual()`. It was fixed in io.js in https://github.com/iojs/io.js/commit/3f473ef141fdc7059928ebc4542b00e2f126ab07 by adding the `assert.deepStrictEqual()`.

**Comment by avdg** [comment] 2015-05-16 17:27
Can't reproduce in node v0.12.3, any need to keep this issue open?

**Comment by jasnell** [comment] 2015-08-27 02:55
At this point someone could take the step of backporting https://github.com/nodejs/node/commit/3f473ef141fdc7059928ebc4542b00e2f126ab07 to v0.12 if they feel it's necessary. But given that this is addressed in v3.x, I'm inclined to close this. Can reopen if necessary.

**Closed by jasnell** 2015-08-27 02:55 UTC
Labels: assert, defer-to-converged, iojs-backport, P-3, S-confirmed-bug
