### ISSUE TITLE
readline not resuming 

### ISSUE THREAD

**Issue by mucbuc** [joyent/node#25360] opened 2015-05-21 12:33 UTC
Adding a time delay breaks the sample app from https://nodejs.org/api/readline.html.

STR: 
1) enter 'a' and press return
2) notice prompt takes a moment to appear 
3) repeat 1 and 2 until prompt doesn't reappear (this happens after less than a dozen tries) 

Expected: Prompt should consistently show up slightly delayed. 

OS: mac 10.9.5 64bit
node -v: v0.12.2

```
var readline = require('readline'),
    rl = readline.createInterface(process.stdin, process.stdout);

rl.setPrompt('OHAI> ');
rl.prompt();

rl.on('line', function(line) {
  switch(line.trim()) {
    case 'hello':
      console.log('world!');
      break;
    default:
      console.log('Say what? I might have heard `' + line.trim() + '`');
      break;
  }
  setTimeout( function() { rl.prompt(); }, 1000 ); // delay
}).on('close', function() {
  console.log('Have a great day!');
  process.exit(0);
});
```

**Comment by jasnell** [comment] 2015-05-26 20:49
This may be the same issue as seen here: https://github.com/joyent/node/issues/9310. @joyent/node-coreteam

**Comment by misterdjules** [comment] 2015-06-08 23:05
@jasnell Confirmed duplicate of #9310 and tested that https://github.com/joyent/node/pull/25475 fixes it. Closing as such. Thank you!

**Closed by misterdjules** 2015-06-08 23:05 UTC
