### ISSUE TITLE
Segfault when 0.12.2 built with gcc 5.1.0 on illumos

### ISSUE THREAD

**Issue by alhazred** [joyent/node#25281] opened 2015-05-12 11:40 UTC
```
# ./node
Segmentation Fault (core dumped)
# mdb core
Loading modules: [ libumem.so.1 libc.so.1 ld.so.1 ]
> $G
C++ symbol demangling enabled
> $c
v8::internal::String::WriteToFlat<unsigned short>+0x7fc(9e025971, 9e026d36, 1f, 3c, 804787c, 6a7)
_ZN2v88internalL39StringReplaceGlobalAtomRegExpWithStringINS0_16SeqTwoByteStringEEEPNS0_6ObjectEPNS0_7IsolateENS0_6HandleINS0_6StringEEENS7_
INS0_8JSRegExpEEES9_NS7_INS0_7JSArrayEEE.constprop.415+0x15f(9044008, 80479a8, 80479a4, 80479a0, 804799c, 8)
v8::internal::Runtime_StringReplaceGlobalRegExpWithString+0x50f(4, 80479a8, 9044008, bcb0a361, 8047980, 80479d8)
0xbcb0a3d6(98a69809, 9ff234f1, 9e026bf9, 9e025971, 98a08091, 98a08091)
0xbcb5bab3(9ff234f1, 9e026bf9, 9e025971, 98a2f271, 9ff360d5, 98a3978d)
0xbcb591c8(98a410b1, 98a3978d, 98a08091, 98a08091, 98a08091, 98a08091)
0xbcb4da13(98a364f1, 98a410b1, 98a41115, 98a40ff5, 8047a6c, bcb46f15)
0xbcb4d0ec(98a41139, 98a364f1, 98a41115, bcb46e81, 10, 0)
0xbcb46f15(0, 0, bcb25601, 0, 0, 0)
0xbcb256aa(bcb4cae0, 9e041d65, 98a364f1, 1, 8047c0c, 90b9cb8)
v8::internal::Execution::Call+0x129(8047b3c, 9044008, 908d014, 908d018, 1, 8047c0c)
v8::Function::Call+0x99(8047bb0, 908d014, 908d018, 1, 8047c0c, 908d050)
node::LoadEnvironment+0x278(909cac8, 0, 9043fd8, 833535f)
node::Start+0x14d(1, 8047d20, 8047cf8, 8324a2a, feffb0a4, 8047d00)
main+0x1b(8047cdc, fe8586e8, 8047d14, 8239df3, 1, 8047d20)
_start+0x83(1, 8047de0, 0, 8047de7, 8047df8, 8047e03)
```

**Comment by misterdjules** [comment] 2015-05-12 23:42
It seems that it might be related to https://github.com/joyent/node/issues/9227 and https://code.google.com/p/chromium/issues/detail?id=152407#c11.

Could you please show us the complete log of the build process. I'm especially interested in seeing the optimization flags used by g++ to build V8.

Are you able to reproduce the problem with gcc 4.x?

**Comment by alhazred** [comment] 2015-05-13 08:37
On 13 May 2015 at 02:44:25, Julien Gilli (notifications@github.com) wrote:
It seems that it might be related to #9227 and https://code.google.com/p/chromium/issues/detail?id=152407#c11.

Could you please show us the complete log of the build process. I'm especially interested in seeing the optimization flags used by g++ to build V8.

Are you able to reproduce the problem with gcc 4.x?

No problem with using gcc 4.8.1. Looks like there are no different flags when building with 4.8.1 or 5.1.0.

But problem is gone when I use -gO2 instead of -gO3.



Alexander

**Comment by misterdjules** [comment] 2015-05-13 16:49
Thank you. Can you try building [io.js](https://github.com/iojs/io.js/), which comes with a newer V8, with GCC 5.1 and -O3, and let us know if you get the same problem?

**Comment by alhazred** [comment] 2015-05-14 08:20
No, io.js doesn't have such problem ;)

**Comment by misterdjules** [comment] 2015-06-16 16:53
This issue in Chromium seems like it could be related too: https://code.google.com/p/chromium/issues/detail?id=412967.

@joyent/node-tsc I don't have the time to investigate potential fixes right now, but if we can validate that the fix mentioned above fixes this specific issue (using GCC 5.1.0 on SmartOS 32 bits), then we should also investigate what other platforms are affected and the extent of the problem.

**Comment by misterdjules** [comment] 2015-06-16 16:55
@joyent/node-tsc Set P-1 because I suspect we would get a lot more reporters of this problem if it affects every recent version of GCC on 32 bits systems. If it turns out this issue is more specific to a single platform or a restricted set of GCC versions, then we can lower the priority.

**Comment by misterdjules** [comment] 2015-06-16 17:02
@orangemocha That's potentially related to the issues you're seeing on the build platform.

**Comment by orangemocha** [comment] 2015-06-16 17:09
The stack trace is very similar to the issue described https://code.google.com/p/chromium/issues/detail?id=412967. It's almost certainly the same issue.

I am going to investigate a couple of options:
1) Backporting the patches listed in the Chromium issue
2) build deps/v8 with -fvect-cost-model=cheap. @joaocgreis verified this solves the issue. But it might have performance implications.

**Comment by misterdjules** [comment] 2015-06-23 17:20
@alhazred Do you have some time to try the fix in https://github.com/joyent/node/pull/25556?

**Comment by alhazred** [comment] 2015-06-23 17:59
I've built janeasystems/node with 5.1, unfortunately same core.

**Comment by misterdjules** [comment] 2015-06-23 18:00
@alhazred Did you build the `joaocgreis-pick-v8-smartos` branch from `janeasystems/node`?

**Comment by alhazred** [comment] 2015-06-23 18:05
Ah.. End of the day :) give me a min

**Comment by misterdjules** [comment] 2015-06-23 18:06
@alhazred No worries, your help is very much appreciated :+1:

**Comment by alhazred** [comment] 2015-06-23 18:13
Bingo! Thank you very much for this :)

**Comment by misterdjules** [comment] 2015-06-23 18:17
That's all thanks to @joaocgreis' work :)

@alhazred Thank you very much to you for helping us solve this! :+1:

**Comment by joaocgreis** [comment] 2015-07-01 17:51
Fixed by https://github.com/joyent/node/commit/48b0ca26161b6a7a8b9804f6a4c96cb0f0509830 and https://github.com/joyent/node/commit/13ea50e927546165fa967f25c46d6e7cf825aade

**Closed by joaocgreis** 2015-07-01 17:51 UTC
Labels: P-1, v0.12, V8
