### ISSUE TITLE
About NodeJs X64 Windows Release

### ISSUE THREAD

**Issue by ridvann** [joyent/node#25531] opened 2015-06-16 19:28 UTC
Hi,

AirServer setup files in the X64 Windows Package???

I do not understand ... Is this a mistake?

Thanks

Best Regards

![image](https://cloud.githubusercontent.com/assets/3194325/8192457/efa5df50-1476-11e5-9af5-6fcbebac3b70.png)

![image](https://cloud.githubusercontent.com/assets/3194325/8192462/fc1108b4-1476-11e5-9c2b-38ecd6762566.png)

**Comment by dnakamura** [comment] 2015-06-16 19:47
Installer looks fine to me. What version are you installing / where did you get the installer?

**Comment by ridvann** [comment] 2015-06-16 19:56
Hi,

I installed the latest version. I downloaded the package
Nodejs.org/download . I sent the following photos.

[image: Satır içi resim 1]

I installed the x86 package. Such a thing did not happen in this package.
So I thought it would be a mistake.

Thanks

2015-06-16 22:48 GMT+03:00 Devin Nakamura <notifications@github.com>:

**Comment by ridvann** [comment] 2015-06-16 19:57
Hi,

I installed the latest version. I downloaded the package Nodejs.org/download . I sent the following photos.

![image](https://cloud.githubusercontent.com/assets/3194325/8193039/0138f23a-147b-11e5-810e-4e9fbc329cf4.png)

I installed the x86 package. Such a thing did not happen in this package. So I thought it would be a mistake.

Thanks

**Comment by misterdjules** [comment] 2015-06-16 21:18
@ridvann Thank you for reporting this issue. It is similar to what other users have mentioned here: https://groups.google.com/forum/#!topic/nodejs/rTmyqw17hHg. 

I'm not able to reproduce the problem. Do you get the same AirServer installer every time you download a new node x64 msi installer?

**Comment by ridvann** [comment] 2015-06-16 23:19
@misterdjules thanks

I found the problem. I think such a situation is causing a proxy server. When I download my home computer, I download the correct package.

That is to say.

![image](https://cloud.githubusercontent.com/assets/3194325/8196576/bd384aac-1495-11e5-8c7f-89261427ea80.png)

The photo above in:

1. Left Properties: I downloaded the package from home
2. Center Properties: Wrong downloaded package
3. Right Properties: AirServer Orijinal package

There are three packages similar to one aspect of this. This file sizes...

![image](https://cloud.githubusercontent.com/assets/3194325/8196646/8ea1700a-1496-11e5-80c3-d410b666129c.png)

The proxy server does not know how such a process.

An interesting case :)

If necessary, files can be accessed from the following link.

https://www.dropbox.com/sh/jjnykxqomheqzis/AAAY44_WAWZB9GMtAo9keCl8a?dl=0

Thanks

Best regards

**Comment by misterdjules** [comment] 2015-06-16 23:34
@ridvann When downloading node's x64 msi installer through that proxy, do you get the air server installer instead every time? Would you mind sharing some information about this proxy so that we can also reproduce this problem on our side?

Thank you!

**Comment by ridvann** [comment] 2015-06-17 00:32
@misterdjules Yes, when I connect to the Internet with proxy servers, downloading the airserv package at a time. When I went to the office tomorrow, I can share the proxy server information.

Thanks

**Comment by ridvann** [comment] 2015-06-18 23:56
@misterdjules I checked the firewall system in the office. I reach the following information.
We use Linux-based firewall. And content filtering proxy server as we use Dansguadian and Squid. These versions do not know. I could not get the information because it comes in the box version.

I wrote a little late. Sorry: |

Thanks

**Comment by n3m6** [comment] 2015-06-20 19:32
I just downloaded the x64 binary from nodejs.org and this happened to me. This is extremely fishy! What is going on?

**Comment by JohnMcLear** [comment] 2015-06-21 01:18
Time for SHA signatures.

**Comment by JohnMcLear** [comment] 2015-06-21 01:20
@n3m6 @ridvann it looks like you are both on compromised networks or compromised machines.

**Comment by fastest963** [comment] 2015-06-21 02:10
I assume if you download it with https it works fine?
https://nodejs.org/dist/v0.12.4/x64/node-v0.12.4-x64.msi

Is there a reason that the nodejs.org site doesn't use https for downloads when you're on https://nodejs.org?

**Comment by n3m6** [comment] 2015-06-21 06:12
@JohnMcLear this is a fresh install of windows on a new machine

@fastest963 I tried downloading it just now. It works, finally!

nslookup on nodejs.org gives this 

Non-authoritative answer:
Name:    nodejs.org
Address:  165.225.133.150

**Comment by jwalton** [comment] 2015-06-21 12:52
Here's a report from someone getting AirServer directly from home, and then spontaneously switching to the correct binary: http://www.reddit.com/r/node/comments/3ajhfc/malware_on_nodejsorg/.

For those affected; if you could post a `traceroute nodejs.org` (linux or OS/X) or a `tracert nodejs.org` (windows) from you affected machine, the results would be interesting.

**Comment by misterdjules** [comment] 2015-06-23 19:36
Downloads from nodejs.org [now use HTTPS by default](https://github.com/nodejs/nodejs.org/pull/127). While it's not a solution to these types of issues, if the problem reporter here is due to a man in the middle attack, using HTTPS should help prevent it.

@ridvann Could you please try to reproduce the problem you have when downloading files behind your proxy and let us know if enabling HTTPS at least warns you or prevents you from download the AirServer installer?

Please be mindful that it only guarantees you that the content you download is sent from nodejs.org, it does not guarantee you that the content hasn't been tampered with. For that, you'll need to verify the digital signatures provided with each releases.

I also started a thread about [a better UX to verify downloads of releases from nodejs.org](https://github.com/nodejs/nodejs.org/issues/144). Your feedback about any concern you may have or about how you'd like to be able to verify downloads would be very much appreciated.

**Comment by ridvann** [comment] 2015-06-26 12:31
@misterdjules The problem did not occur with HTTPS.

Thank you for your interest

Best regards

**Comment by misterdjules** [comment] 2015-06-29 23:02
@ridvann Do you mean that before nodejs.org changed download links to be HTTPS by default, you could always (100% of the time) reproduce the problem (download the AirServer installer instead of the Node.js installer) when downloading Node.js from behind your proxy, and that now when downloading Node.js behind your proxy you always get the Node.js installer?

If so we will close this issue. Thank you again for your help! :+1:

**Comment by misterdjules** [comment] 2015-07-07 22:15
@ridvann Closing as it seems to be fixed, but please feel free to comment if I misunderstood [your latest comment](https://github.com/joyent/node/issues/25531#issuecomment-115661155) and I'll reopen.

**Closed by misterdjules** 2015-07-07 22:15 UTC
Labels: installer, P-1, windows

**Comment by ridvann** [comment] 2015-07-08 22:35
@misterdjules  If I write something similar again.

Thank you very much for your concern.

Best Regards
