### ISSUE TITLE
dns.js crash

### ISSUE THREAD

**Issue by barn3y** [joyent/node#25327] opened 2015-05-15 00:08 UTC
I'm seeing a very rare crash from node 0.10.38's dns.js library. Not sure how to reproduce it (yet).

    TypeError: Cannot call method 'indexOf' of undefined
      at Object.onanswer [as oncomplete] (dns.js:121:51)

Digging into the source, it's hitting this line:

    callback(null, addresses[0], addresses[0].indexOf(':') >= 0 ? 6 : 4);

addresses comes from a wrapped getaddrinfo call, so I'm guessing somehow on the system I'm using (ubuntu 14.04 LTS running kernel 3.13.0-46), it's capable of returning addresses an an array with a null/undefined entry, which dns.js doesn't guard against.

Also, I had a look at the 0.12 source to see if it was fixed there, the code has been significantly updated, but the same crash still seems possible, in fact 0.12 assumes the addresses array exists, which 0.10 did not.

I'm not sure of the right path to resolve this, would appreciate any suggestions.

**Comment by jasnell** [comment] 2015-05-15 00:25
Hmm.. possibly some kind of race condition happening that's not being guarded against. If at all possible, it would be helpful if you can put together a simple test case that demonstrates the problem (even if only intermittently). Which os are you using?

**Comment by barn3y** [comment] 2015-05-15 00:30
I have found no way to reproduce it as yet, but have seen it crash in a production environment twice.

Unfortunately, because the crash comes from an asynchronous response, I don't even know what called the lookup function (which is where the crash occours), nor what the address being looked up is.

The system is running node.js 0.10.38 on Ubuntu 14.04 LTS, running kernel 3.13.0-46.

If I find anyway to reproduce it, I will update this issue.

**Comment by jasnell** [comment] 2015-05-15 00:55
:+1: like I said, I suspect that there's some kind of race condition happening but cannot be certain. It would likely be a worthwhile exercise to dig through and profile dns.js a bit more. Either way tho, let us know if you're able to isolate the problem and I'll mark a note to investigate further as time permits.

**Comment by misterdjules** [comment] 2015-05-15 18:12
Closing as a duplicate of #8698. Your detailed description of the issue will definitely help us investigate it and is very much appreciated.

I would suggest the same as in [one of my comments in that issue](https://github.com/joyent/node/issues/8698#issuecomment-62826169): instrument your code so that when the error is thrown, we can get a better idea of the context and see if there's a pattern we can identify.

**Closed by misterdjules** 2015-05-15 18:12 UTC
