### ISSUE TITLE
NodeJS 0.12.2 slower than 0.12.1

### ISSUE THREAD

**Issue by vitaly-t** [joyent/node#14384] opened 2015-04-02 02:59 UTC
I'm developing my own library on GitHub, one that relies heavily on use of Promises, and whenever I make a change I always pay attention to the timings I get while running tests through Travis CI, using Node 0.10.x and Node 0.12.x, and up until now, all my tests were running on average 15% faster with Node 0.12.0 and 0.12.1 than Node 0.10.x, and suddenly now that Travis CI is using 0.12.2 also, my tests under Node 0.12.2 are slower than the same under Node 0.10.x

Check the build details: https://travis-ci.org/vitaly-t/pg-promise/builds

What could have slowed down Node 0.12.2?

**Comment by trevnorris** [comment] 2015-04-03 20:54
V8 native promises are freakishly slow. If you require any type of performance while using Promises then I'd recommend bluebird.

**Comment by vitaly-t** [comment] 2015-04-04 00:05
Bluebird is what I'm using already anyway. The question was about the relative speed change between Node JS 0.10.x and 0.12.x, not absolute speed.

**Comment by trevnorris** [comment] 2015-04-04 14:37
TBH without a test case it's difficult to say what could be slower in your specific case. Are you using the vm module in your tests?

**Comment by vitaly-t** [comment] 2015-04-04 15:05
I don't even know what vm is, so probably no. I'm just reading timings I'm getting on Travis CI when all my tests are run.

**Comment by jryanearl** [comment] 2015-06-21 01:57
We just bumped into the "super slow version of V8" issue on nodejs-0.12.  This code takes 3x as much time on 0.12.4 than it does on 0.10.35 to execute:

var keys = ["5613","f9fa","45cb","b7c7","7556","f23b","e697","b75d","efd5","aafe","ca3d","7231","81c6"];

for (var i=0; i<100000; i++) {
 var obj = {};
 for (var index in keys) {
   obj[keys[index]] = {};
 }
}

**Comment by vitaly-t** [comment] 2015-06-21 12:06
@jryanearl 
Since you are building 100,000 objects here, each with 13 properties, I would suspect that the new V8 of trying to release memory in parallel, which would slow down the test.

Can you get similar 3x slow-down figures with a smaller loop, like 10,000?

**Comment by jryanearl** [comment] 2015-06-21 18:37
Yes, we see similar 3x performance hit between 0.10 and 0.12 with 10000 iterations as well, test2.js has 10000 and test.js has 100000 iterations below.  Note I expect there is some per run startup/optimization overhead involved as well as the results are better-than-linear per iteration between 10000 and 100000 iterations:

$ time /data/nodejs-0.12/bin/node test2.js

real	0m0.336s
user	0m0.299s
sys	0m0.036s

$ time /data/nodejs-0.10/bin/node test2.js

real	0m0.129s
user	0m0.121s
sys	0m0.007s

$ time /data/nodejs-0.12/bin/node test.js

real	0m2.428s
user	0m2.347s
sys	0m0.084s

$ time /data/nodejs-0.10/bin/node test.js

real	0m0.818s
user	0m0.811s
sys	0m0.012s

$ /data/nodejs-0.10/bin/node --version
v0.10.35
$ /data/nodejs-0.12/bin/node --version
v0.12.4

You can, of course, test this yourself with the code snippet above.  We bundle our own nodejs package in a manner that let's us install multiple major versions on a single host/OS image.  These tests were done back-to-back, on the same bare-metal load-testing host.  Note, this translates directly into node-0.12 performing significantly worse for our application.  In our real-world application response times almost doubled going from nodejs 0.10 => 0.12 in additional to using more CPU.

**Comment by jasnell** [comment] 2015-06-25 19:26
@trevnorris ... any reason to keep this open?

**Comment by vitaly-t** [comment] 2015-06-25 19:33
@jasnell ... is performance degradation not an issue for Node JS?

**Comment by trevnorris** [comment] 2015-06-25 19:43
From all the information I gather, the performance degradation discussed here is because of V8. Not because of changes to the node API. The only possible remedy is to further upgrade, which won't happen in the v0.12 branch.

**Comment by vitaly-t** [comment] 2015-06-25 19:47
@trevnorris is there a place to log issues against V8 then?

**Comment by jasnell** [comment] 2015-06-25 19:51
@vitaly-t ... you can report V8 issues directly against their github repo. One suggestion would be to test the performance on the latest io.js, which uses a much more recent version of V8. @domenic may be able to provide some insights. I'm going to close this for now. We can reopen if necessary.

**Comment by trevnorris** [comment] 2015-06-25 19:51
@vitaly-t v0.12 uses an ancient branch of V8 (3.14 iirc). You'd have to test against latest (4.5) and determine if there's still a regression before V8 would consider it an issue. You may want to start simply by running it against latest io.js. If you can build it, then against the `next` branch of io.js would be optimal.

**Closed** 2015-06-25 19:51 UTC

**Comment by jryanearl** [comment] 2015-06-25 19:59
For the record, we tested on io.js before I posted here, and it was even slower on that version of v8 for the code snippet.  It seems it would be better to go backwards with v8 than forwards actually.  As is, 0.12 is going to be unusable for us due to be significantly slower than 0.10.

**Comment by vitaly-t** [comment] 2015-06-25 20:03
@jryanearl , ha-ha, 0.10.x is here to stay for a long time, as the last version that performs well, and the last version that doesn't break all your IPv4 code ;)

**Comment by trevnorris** [comment] 2015-06-25 21:04
Let me show why I recommended to try this on the `next` branch of io.js. ;-)
```
v0.10:  420ms
v0.12: 1160ms
v2.x:  2430ms
v3.x:   420ms
```
And using the following example that more closely adheres to V8 performance practices:
```js
var keys = ["5613","f9fa","45cb","b7c7","7556","f23b","e697","b75d",
            "efd5","aafe","ca3d","7231","81c6"];

for (var i = 0; i < 1e5; i++) {
  var obj = {};
  for (var j = 0; j < keys.length; j++) {
    obj[keys[j]] = {};
  }
}
```
I get the following times:
```
v0.10: 280ms
v3.x:  240ms
```
It also gains plenty of performance advantages in more complex cases because of improvements in areas like garbage collection. You should also expect to see even better performance in the future as TurboFan is flushed out.

**Comment by vitaly-t** [comment] 2015-06-25 21:08
@trevnorris , where's the Like button? :) :+1:

**Comment by jryanearl** [comment] 2015-06-25 21:12
Where are you pulling io.js v3.x from?  I only see branches up to 2.3.x, which is what we tested with and saw the even higher times.

**Comment by dudeche** [comment] 2015-06-25 21:24
Quick question, how does this all relate to the io.js/node merger? It feels like the recommendation right now is to use io.js if you're having problems with node 0.12.  FWIW, we're seeing the same kind of degradation going from node 0.10 -> 0.12.  Definitely don't want to hijack this thread, just curious if there's a roadmap/plan.

**Comment by trevnorris** [comment] 2015-06-25 21:24
@jryanearl It's the `next` branch. Will become the v3.x release once a few quirks are worked out. But will be coming soon.

**Comment by trevnorris** [comment] 2015-06-25 21:27
@dudeche One thing you'll want to consider is that no io.js release has LTS support. This is also being worked out by the LTS WG (https://github.com/nodejs/lts), but there hasn't been any resolution so far. So which way you go will depend on your needs.
