### ISSUE TITLE
Repeat unref'd interval persists program until next interval

### ISSUE THREAD

**Issue by mhmeadows63** [joyent/node#7327] opened 2014-03-18 02:46 UTC
Bug: Repeat unref'd interval persists program until next interval

After the ref'd timeout fires, the unref'd interval should not persist the program,
... but it does until the next time the unref'd interval fires.
```
                  (should-exit-here)     (actually-exits-here)
                              |                   |
                              v                   v
(time)-------------------------------------------->
         ^                   ^                   ^
         |                   |                   |
        300(1st interval)    |                   |
                            350(timeout)         |
                                                600(2nd interval)
```

// This is an issue for long unref'd intervals such as for garbage-collection.

```javascript
var assert = require('assert');
var unref_interval = 0;

setInterval(function() {
    ++unref_interval;
}, 300).unref();

setTimeout(function() {}, 350);

process.on('exit', function() {
    assert.strictEqual(unref_interval, 1, "Repeat unref'd interval persists program until next interval");
});
```

**Comment by jasnell** [comment] 2015-05-29 16:00
Currently unable to reproduce on osx 10.10.3 with current v0.10 and v0.12 or io.js. Doesn't mean it's resolved yet tho. @joyent/node-coreteam ... thoughts on this one?

**Comment by Fishrock123** [comment] 2015-05-29 16:03
This looks suspiciously like https://github.com/nodejs/io.js/pull/1231

**Comment by jasnell** [comment] 2015-05-29 16:06
Thanks... I thought I remembered seeing something similar but couldn't recall the specifics. I'll test on windows and ubuntu either later today or monday but I suspect this one has been resolved.

**Comment by jasnell** [comment] 2015-06-24 19:46
Closing. Appears to be resolved in io.js. Will pick up the fix or we can backport.

**Closed by jasnell** 2015-06-24 19:46 UTC
Labels: defer-to-converged, iojs-backport, timer
