### ISSUE TITLE
0.12.3 on Windows XP give not valid win32 application error

### ISSUE THREAD

**Issue by deliverymanager** [joyent/node#25348] opened 2015-05-18 17:13 UTC
I tested on a Windows XP platform.
a) 0.10.33 works fine.
b) 0.12.2 works fine
c) 0.12.3 after installing without a problem, I try to open the Node.exe and it gives me an error "node.exe is not a valid win32 application"

I have also tested the same win32 x86 0.12.3 version on a windows 7 platform and it works fine.
So, probably, this is related to a windows XP problem.

**Comment by jasnell** [comment] 2015-05-18 17:50
duplicate of https://github.com/joyent/node/issues/25347

**Comment by misterdjules** [comment] 2015-05-18 20:32
@orangemocha Do you have some time to investigate?

**Comment by orangemocha** [comment] 2015-05-19 18:20
Not a dupe of #25347, as that one was reported on Windows 7, and this issue is specific to Windows XP.

Most likely would need to backport https://github.com/nodejs/io.js/commit/e8d08503c7821e8c92e9fa236ed7328e9bdfe62a

**Comment by jasnell** [comment] 2015-05-19 18:23
@orangemocha ah... ok.. missed that distinction entirely.

**Comment by JimHolloman** [comment] 2015-05-19 22:09
I have the same issue on XP, 32-bit.  Both the installation (.msi) package and the stand-alone node.exe file (I downloaded both) provide the message "node.exe is not a valid win32 application". The npm provides the same error with the program named changed to npm.exe.

I wonder if someone packaged the 64-bit code as a 32-bit install (.msi) and stand-alone program (node.exe).

**Comment by orangemocha** [comment] 2015-05-22 15:23
Ok, the problem is the gyp/project files don't explicitly specify a subsystem version, which results in the default being used. The default changed from VS 2010 to VS 2012 and later. So this means that one of the release machines still has VS 2010. (@misterdjules we should probably fix that or at least try to document it in an asset sheet). https://github.com/nodejs/io.js/commit/e8d08503c7821e8c92e9fa236ed7328e9bdfe62a fixes the issue. Opening a PR shortly.

**Comment by orangemocha** [comment] 2015-05-22 15:48
Had a chat with @misterdjules and he told me that the release machines have both VS 2010 and 2013. So the change that probably introduced the regression is https://github.com/joyent/node/commit/a58b17456a7fa4ff846c4883b96d6dee7e46a62f, where we select a different toolset version.
Since that change is not in v0.10, the v0.10 release still works in XP. I will cherry pick https://github.com/joyent/node/pull/25367 into v0.10 later.

**Comment by misterdjules** [comment] 2015-05-23 00:28
Fixed by https://github.com/joyent/node/commit/3122052890e838220b49794de924b323675b3b18. This fix will be included in the upcoming v0.12.4 release. Thank you!

**Closed by misterdjules** 2015-05-23 00:28 UTC
Labels: P-1, windows

**Comment by misterdjules** [comment] 2015-05-23 06:51
@orangemocha @deliverymanager @JimHolloman There's a new candidate release with the fix for this issue here: http://nodejs.org/dist/v0.12.4/. Could you please try to install this version on Windows XP and let us know if it solves your problem? Thank you!

**Comment by deliverymanager** [comment] 2015-05-23 07:45
Yes I can confirm that in 0.12.4 the bug is resolved.
It is working fine.

**Comment by misterdjules** [comment] 2015-05-23 07:50
@deliverymanager Thank you! In the meantime I was also able to setup a Windows XP VM, and I also verified that the new binaries/installers work on XP.

**Comment by appopen** [comment] 2015-05-23 14:25
Gentlemen, Though I do run Win 7 for fat apps sing VS 2013, my web work is done in Win XP. Thank you so much for resolving this Win XP issue; it allows many of us to continue using more modern versions of node.

**Comment by misterdjules** [comment] 2015-05-23 15:02
@appopen Thank you for the support! :+1:

**Comment by Dineshkumar2401** [comment] 2015-10-30 11:56
windowsXP32bit install to odoo9 lessc cmd  problem to soluction  to install lessc  plugins using cmd panel ref to url:http://lesscss.org/usage/#developing-less problem all solved.....
