### ISSUE TITLE
debugging node.js project with Eclipse IDE

### ISSUE THREAD

**Issue by francesco9** [joyent/node#9281] opened 2015-02-25 15:05 UTC
Hi there,
i've been trying for four hours to debug a node.js project with Eclipse Luna IDE. 
My project is made of several node.js modules and i need to debug the code setting breakpoints around all modules but what happened is that it jumps only at the first breakpoint (at main.js module) end misses all the other breakpoints. I've already debugged with eclipse some time ago but i don't remember what i've done more.I remember that the problem was resolved declaring "module.exports.functioname"...but now it still doesn't work! I have installed node-eclipse plugin and V8 debugger. It doesn't jump into the other node.js modules. Do you have any suggestion,please?
Thanks.

**Comment by jasnell** [comment] 2015-03-04 03:26
Which version of node, which platform? I'm not familiar with the changes myself, but apparently there were quite a few updates to the v0.12 debugger so it's likely something on the Eclipse tooling side that may need to be updated. Without more information it would be impossible to say for sure.

**Comment by francesco9** [comment] 2015-03-04 08:50
The version of node is 0.12.0, Eclipse Luna IDE when i go in Eclipse on Preferences ---> Nodeclipse i see above: 
Nodeclipse 0.17.0.201409260936 Eclipse 4.4.0.v20140925 Java 1.8.0_31 OS: win32,x86_24.
Everything is almost the latest version.
Do you have any idea please? Thanks.

**Comment by jasnell** [comment] 2015-06-25 18:48
I would follow up with the nodeclipse project first. Closing this for now. Can reopen if it becomes clear that the issue is within node

**Closed by jasnell** 2015-06-25 18:48 UTC
