### ISSUE TITLE
REPL doesn't read commands from redirected input stream

### ISSUE THREAD

**Issue by segrey** [joyent/node#25791] opened 2015-07-31 21:32 UTC
Node 0.12.7
1. Start node REPL with redirected standard input stream: 
```bash
$ cat | node
```
2. Type `console.log('Hello')` and press Enter
3. No output, but `Hello` was expected
4. Close streams by pressing Ctrl+D => `Hello` is output

**Comment by jasnell** [comment] 2015-08-03 16:51
Actually, this is the behavior you'd want to see. Consider the following.

1. Run `cat | node`
2. Then type in the following, pressing enter at the end of each line:
```javascript
function add(a,b) {
  console.log(a+b);
}
add(1,2);
```
3. Then press Ctrl+D

When running node in this way, you're giving node input on stdin -- which it's going to expect is no different than receiving a js file. It's not going to run interactively like the REPL -- which is only run if there is *no* script provided on stdin.

**Comment by jasnell** [comment] 2015-08-03 16:52
Closing. Not a bug.

**Closed by jasnell** 2015-08-03 16:52 UTC

**Comment by segrey** [comment] 2015-08-03 20:37
Thanks for the explanation. One thing I'm not sure I understand is the logic that enables the REPL.
I mean in both cases (`$ cat | node` and `$ node`) node processes have standard input streams and no JavaScript files passed in as arguments. However, the behaviors are different.

**Comment by jasnell** [comment] 2015-08-03 20:56
When node starts, if there is no input on stdin, it will create an instance of REPL that will perform it's own interaction with stdin. With `cat | node`, node is being explicitly launched with input from stdin... if if that input ends up being empty.

**Comment by segrey** [comment] 2015-08-03 21:08
>if there is no input on stdin, it will create an instance of REPL

IIUC, in both cases there is no input on stdin when node starts. Maybe it checks TTY?
