### ISSUE TITLE
fs.readdirSync("../") fails on OS X, works on Windows.

### ISSUE THREAD

**Issue by webprofusion-chrisc** [joyent/node#25374] opened 2015-05-24 01:37 UTC
In a jake build script a reference to fs.readdirSync("../") works on Windows but not on Mac OS X. It starts working again if I just precede the call with:

console.log("process cwd:"+process.cwd());

It seems like calling process.cwd() inits the cwd for fs on OS X, but is not required on Windows.

**Comment by cjihrig** [comment] 2015-05-24 02:39
What versions of Node and OS X are you using? Can you provide a simple test that reproduces the issue, with no external dependencies. `fs.readdirSync('../')` works fine from the REPL for me with the 0.12 branch.

**Comment by webprofusion-chrisc** [comment] 2015-05-24 11:46
I'm seeing this on Mac OS X Yoesmite 10.10.3 with node 0.12.3 - the error is no such file or directory. I'll see if I can reproduce with a simple test case.

**Comment by jasnell** [comment] 2015-05-26 19:49
I'm unable to reproduce running on yosemite 10.10.3 using node v0.12.3.

**Comment by EngineeringMode** [comment] 2015-05-27 00:05
Unable to replicate on OS X Yosemite 10.10.2

**Comment by jasnell** [comment] 2015-05-27 00:26
Closing due to inability to replicate issue

**Closed by jasnell** 2015-05-27 00:26 UTC
