### ISSUE TITLE
JSON.parse

### ISSUE THREAD

**Issue by Arhangel64** [joyent/node#9288] opened 2015-02-26 06:18 UTC
Hello everyone.
Noticed some issue with JSON.parse. I have ~18mb JSON file i'm using like a database. Since the 12 version was released it takes my computer around 2-3 minutes to parse that file. It also takes machine ~ 2GB of RAM, sometimes process fails with fatal error OUT OF MEMORY. Seems like there's a leak somwhere.

**Comment by CGavrila** [comment] 2015-02-26 10:00
@Arhangel64: could you please specify which Node versions you see the difference for? Also, is it possible for you to provide the JSON file or at least its format?

**Comment by Arhangel64** [comment] 2015-02-26 12:03
Not sure, but i guess it's between 0.10.36 and 0.12.0.
that json is situated here
https://github.com/Arhangel64/lexic.js/blob/master/dic/ru.json

**Comment by CGavrila** [comment] 2015-02-26 12:40
It seems that you are right. I tested with v0.10.36 and v0.12.0 on Ubuntu 12.04 and I got results similar to what you're describing.

Scripts used:
```
var fs = require('fs');
var obj;
fs.readFile('ru.json', 'utf8', function (err, data) {
  if (err) throw err;
  obj = JSON.parse(data);
});
```

and
```
var fs = require('fs');
var obj;
var start_time = Date.now();
var obj = JSON.parse(fs.readFileSync('ru.json', 'utf8'));
console.log(Date.now() - start_time);
```

For the async one I got:
```
v0.10.36 -  1.1s
v0.12.0   -  33.7s
```

For the sync one I got:
```
v0.10.36 -  1.1s
v0.12.0   -  28s
```

After a bit of investigation, it seems that `JSON.parse()` is the culprit, and not the `fs` module. This pretty much means that the problem is at V8 level and there's little chance of anyone fixing this, unless the whole V8 version is changed.

**Comment by micnic** [comment] 2015-02-26 13:41
I tested this json with io.js also and it seems that the problem persists in the recent version of v8 (4.1.0.14)

**Comment by piscisaureus** [comment] 2015-02-26 14:16
Maybe post this to the v8 issue tracker (https://code.google.com/p/v8/issues/list) then?

**Comment by CGavrila** [comment] 2015-02-26 14:26
Definitely should, especially since `JSON.parse()` is a such a core function in Javascript. I find it strange that there aren't more people complaining about it. 

@Arhangel64: maybe you could use some NPM module in the meantime? There are separate NPM modules for parsing JSON - e.g. [https://github.com/creationix/jsonparse](https://github.com/creationix/jsonparse)

**Comment by Arhangel64** [comment] 2015-02-26 16:38
Thank you so much!
I've post that issue to v8 developers, (https://code.google.com/p/v8/issues/detail?id=3925&thanks=3925&ts=1424968600).
What should we do with this issue?

**Comment by Arhangel64** [comment] 2015-05-12 11:12
Hello everybody! V8 team reports - they fixed that bug! Are you planning to update V8 in node?
https://code.google.com/p/v8/issues/detail?id=3925&thanks=3925&ts=1424968600

**Comment by micnic** [comment] 2015-05-12 12:08
I think you should wait for the first Node Foundation release :)

**Comment by jasnell** [comment] 2015-05-12 14:46
The V8 version will definitely be updated in the first node.js foundation release so that'll be something to look forward to. There's always the possibility of attempting to backport the fix into the downlevel V8 but that can get messy.

**Comment by jasnell** [comment] 2015-06-05 15:31
Going to close this issue here. The fix would likely be expected in the converged stream.

**Closed by jasnell** 2015-06-05 15:31 UTC
