### ISSUE TITLE
New release, please!

### ISSUE THREAD

**Issue by dbkaplun** [joyent/node#25474] opened 2015-06-03 21:16 UTC
With the new [libuv/libuv@v1.6.0](https://github.com/libuv/libuv/releases/tag/v1.6.0) release, NodeJS should no longer be utterly broken on OSX. (For details see libuv/libuv#304.) Please cut a new release. Thank you!

**Comment by CGavrila** [comment] 2015-06-05 11:19
Until that actually gets released, I guess you could compile it yourself. 

Steps:
```
git clone git@github.com:joyent/node.git
git checkout v0.12.4
cd deps/
rm -rf uv
git clone git@github.com:libuv/libuv.git uv
cd uv
git checkout 1.6.0
cd ../..
./configure && make -j 8
make test //optional
```

Should merge cleanly.

**Comment by misterdjules** [comment] 2015-06-08 22:58
@dbkaplun Thanks for reporting this problem. @joyent/node-tsc made the decision to not do a v0.12.5 release for this specific issue only for the following reasons:

1. It breaks only on OSX, not 100% of the time and the only reproduction there is today is using the REPL. In other words, it seems it affects only a minority of users.
2. It seems it's been broken since node v0.11.12, and since then we haven't seen a significant number of reports for this specific issue, which seems to confirm 1).

Of course, feel free to let us know if you disagree with the points mentioned above. There are other issues which together would make a good v0.12.5 release, and as a consequence it should not be to long though.

Also, closing as a duplicate of https://github.com/joyent/node/issues/9310.

Thank you!

**Closed by misterdjules** 2015-06-08 22:58 UTC

**Comment by dbkaplun** [comment] 2015-06-08 23:45
@misterdjules, thank you for your consideration of this issue.

First of all, this bug is not a duplicate of #9310, as this bug calls for a new release, though it is related.

Yes, this issue only affects OSX, and yes, sometimes the code will work, but the issue is a race condition: if the user uses the program long enough, invariably the user will be affected. As a matter of fact, this race condition breaks every CLI NodeJS app on OSX. There are many CLI apps that are suffering because NodeJS is not a stable enough platform.

From what I understand, the decision to make a new NodeJS release is arbitrary. I can sympathize with the desire to make a "good" release but such a desire shouldn't inhibit NodeJS from functioning as it should. I think a point release is an easy solution: it won't cost anything, and will fix many problems.

Thanks again, and I hope to see v0.12.5 soon!

**Comment by misterdjules** [comment] 2015-06-09 00:39
@dbkaplun It is very often difficult for members of the TSC to have a good understanding of what applications are affected by a bug. So far, it seems only a handful of issues have been opened for this problem. This is why during the latest TSC weekly call, the [decision had been made to not rush a release to fix that specific problem](https://github.com/joyent/node-website/pull/124/files#diff-7e9f22b784ade669eff430c510d515adR35).

The fact that it's been present since node v0.11.12 also lead us to think that waiting for at most a few weeks to release a fix would not make a big difference.

But we may very well be wrong, and if you can provide us with a different perspective on how this issue affects a significant number of users, we'll be happy to reconsider this decision.

Also, the goal is not to have a "better" release by not doing one asap that only fixes this issue, it is to not rush things so that we don't introduce any regression.

Thank you very much for your support, we'll do our best so that the v0.12.5 release is not too far from now.

**Comment by dbkaplun** [comment] 2015-06-09 12:18
I can give one instance of how this affects a significant number of users, and the reason I wrote this issue in the first place: I am the maintainer of the npm package [slap](https://www.npmjs.com/package/slap) ([github](https://github.com/slap-editor/slap)), which is a CLI text editor written in NodeJS. This bug means that, on Node >v0.10, the editor simply stops responding every ~12th keystroke, leaving a very poor experience for users (see slap-editor/slap#156). Seeing as slap gets over 4,000 downloads a month (conservatively speaking), I would say that the issue does affect a significant number of users.

I think NodeJS is the best platform for a variety of reasons, not the least of which being approachability for the novice, and amount of packages and libraries written for NodeJS. I have contributed to NodeJS a few times in the form of [code](https://github.com/joyent/node/commits/master?author=dan@beardtree.com) and [issues](https://github.com/joyent/node/issues/created_by/dbkaplun), and you have been very receptive in the past. I hope we can continue to make NodeJS the best software platform!

**Comment by misterdjules** [comment] 2015-06-09 16:18
@dbkaplun Thank you very much for the detailed info regarding the impact of that issue on slap. That definitely helps prioritize things. There's a new OpenSSL release coming up on Thursday, so it's likely we'll need to do a release soon, probably next week. There's a good chance the libuv upgrade would be included in such a release.

Does that help?

**Comment by dbkaplun** [comment] 2015-06-22 14:45
*eagerly anticipates new release*

**Comment by misterdjules** [comment] 2015-06-22 20:49
@dbkaplun node v0.12.5 [has just been released](http://blog.nodejs.org/2015/06/22/node-v0-12-5-stable/). I hope that helps!
