### ISSUE TITLE
let not working in for with continue 

### ISSUE THREAD

**Issue by mikalai-sauchanka** [joyent/node#9315] opened 2015-03-02 13:58 UTC
node 0.12.0. Currently this code runs infinitely (i is always 1):

```javascript
'use strict';

for (let i = 0; i < 2; i++) {
    console.log(i);
    continue;
}
```

**Comment by cjihrig** [comment] 2015-03-02 14:01
Closing as a duplicate of #9113

**Closed by cjihrig** 2015-03-02 14:01 UTC
