### ISSUE TITLE
Is there a way for one TCP packet one 'data' event? #node 0.10.35

### ISSUE THREAD

**Issue by dayuoba** [joyent/node#15443] opened 2015-04-14 15:28 UTC
As API doc mentioned.socket.nodelay defaults to `true`,but even i call `socket.setNoDelay(true)`,it didn't work well..
reproduce code:
server.js
```
var net = require('net');
var fs = require('fs');
var domainSock = '/tmp/domainSock';

var server = net.Server(function handle(socket) {
	socket.setNoDelay(true);
	socket.on('data', function(data) {
		console.log('*');
		console.log(data.toString());
		console.log('*');
	});
});

server.listen(domainSock);

server.on('error', function(e) {
	if (e.code == 'EADDRINUSE') {
		console.log('Address in use, retrying after 1minute..');
		setTimeout(function() {
			try {
				fs.unlinkSync(domainSock);
				//server.close();
			} catch (e) {
				console.log(e);
			}
			server.listen(domainSock);
		}, 1000);
	}
});
```
client.js
```
var net = require('net');

var socket = net.connect('/tmp/domainSock');
socket.setNoDelay(true);
socket.on('connect', function listener() {
	console.log('connect');
	socket.write('data');
	socket.write('data');
	socket.write('data');
	socket.write('data');
	socket.write('data');
	socket.write('data');
	socket.write('data');
	socket.write('data');
	socket.write('data');
	socket.write('data');
});
```
####every time testing.the output is different.i don't know why.did i miss something?
output:
```
//first time
*
datadatadata
*
*
datadatadatadatadatadatadata
*
//second time
*
datadatadatadatadatadatadata
*
*
datadatadata
*

//third time
*
data
*
*
datadatadatadatadatadatadatadatadata
*
```
EDIT:I must say, i want one TCP packet one 'data' event was called.

**Comment by dayuoba** [comment] 2015-04-15 07:48
No one meets this problem?
i'd changed the string written above 'data' to 'how about making the message verylonggggggggggggggggggggggggg'.
i got the regular output :  
```
*
how about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggg
*
*
how about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggg
*

```
only first time call wirte(),it will send data immediately.

**Comment by silverwind** [comment] 2015-04-17 17:02
There's two reasons why you're seeing this:

- You need to run `.setNoDelay()` after the socket has connected for it to work.
- The TCP stack might coalesce packets. If you inspect the traffic in WireShark, you should see single packets.

Check out https://github.com/iojs/io.js/issues/906#issuecomment-77616094 for some more discussion.

**Comment by dayuoba** [comment] 2015-04-18 03:01
thanks for your response @silvewind
tried as you said 
```
var net = require('net');

var socket = net.connect('/tmp/domainSock');

socket.once('connect', function listener() {
//socket.on
	console.log('connect');
	socket.setNoDelay(true);
	socket.write('how about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggg');
	socket.write('how about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggg');
	socket.write('how about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggg');
	socket.write('how about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggg');
	socket.write('how about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggg');
	socket.write('how about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggg');
	socket.write('how about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggg');
	socket.write('how about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggg');
	socket.write('how about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggg');
	socket.write('how about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggg');
});
```
it still doesn't work...
i'm not sure if there are some differences between TCP and UnixSocket
pls have a note,i use `.listen(path)` ,not the same as you mentioned at [iojs/io.js#906 (comment)}(https://github.com/iojs/io.js/issues/906#issuecomment-77616094)

**Comment by dayuoba** [comment] 2015-04-18 03:02
thanks for your response @silvewind
tried as you said 
```
var net = require('net');

var socket = net.connect('/tmp/domainSock');

socket.once('connect', function listener() {
//socket.on
	console.log('connect');
	socket.setNoDelay(true);
	socket.write('how about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggg');
	socket.write('how about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggg');
	socket.write('how about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggg');
	socket.write('how about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggg');
	socket.write('how about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggg');
	socket.write('how about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggg');
	socket.write('how about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggg');
	socket.write('how about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggg');
	socket.write('how about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggg');
	socket.write('how about making the message verylonggggggggggggggggggggggggghow about making the message verylonggggggggggggggggggggggggg');
});
```
it still doesn't work...
i'm not sure if there are some differences between TCP and UnixSocket
pls have a note,i use `.listen(path)` ,not the same as you mentioned at [iojs/io.js#906 (comment)}(https://github.com/iojs/io.js/issues/906#issuecomment-77616094)

**Comment by silverwind** [comment] 2015-04-18 14:09
I think what you're seeing is coalascing of socket writes. One 'data' event isn't always one packet. If you look at it in wireshark, you should see it sending each call in a single packet.

If this is someting considered an issue or not, I can't answer. You should handle your data in a streaming way.

**Comment by dayuoba** [comment] 2015-04-18 16:25
@silverwind thanks,i understand what you said.But what i need is one packet one 'data' event
is there any way of implemention of this?

**Comment by silverwind** [comment] 2015-04-19 09:26
I don't fully understand if this is caused by the kernel or by node. It may or may not be a node bug, will research.

**Comment by misterdjules** [comment] 2015-05-07 00:46
@dayuoba Thank you for reporting this issue! There's already an issue that describes `setNoDelay` being a no-op if the socket is not connected: https://github.com/joyent/node/issues/8572.

Would you mind editing the title and description of this issue so that it better represent the remaining unknown issue, which is that for multiple TCP packets seem to result in only one `'data'` event, and that there's no way to change that?

**Comment by dayuoba** [comment] 2015-05-07 02:54
@misterdjules ok, thanks for your response.but it did not resolve my issue,and right now i mush add a 'EOF' like symbol at the end of each message for what i want.

**Comment by ravi** [comment] 2015-05-07 03:21
TCP is not a datagram protocol. There is no "packet" at the transport layer.

**Comment by dayuoba** [comment] 2015-05-07 07:45
@ravi i don't know the protocal details,but as i use setNoDelay(true),what i think is it should send data immediately,so i regart it as a `packet` and what  i want is that the server side should emit the 'data' event immediately.

**Comment by ravi** [comment] 2015-05-07 13:41
@dayuoba that's a fair expectation: setting setNoDelay(true) should disable Nagle's algorithm at the TCP layer. I write to warn you that flushing TCP buffers in real-time provides no guarantee that they will be sent into and across the network in the same segment sizes you wrote them out in from the application, and more importantly, you can have no guarantee that they will be passed (by the network stack) to the receiver with the same packetization. In other words TCP_NODELAY does not imply message boundaries or guarantees message sizes. It just says to the kernel, don't buffer up bytes waiting for TCP acknowledgements, but send them down the wire (TCP window, etc, permitting) as you receive it. How these fragments get chopped up within the network and reassembled at the receiver is out of the scope of this setting (disclaimer: IP has some near-obsolete flags for fragmentation/reassembly control, but let's ignore those).

If you perform one write operation of 300 bytes every 100 milliseconds, the only way Node, sitting atop TCP, can provide them back to the receiver in 300 byte chunks at a time is by imposing its own message boundaries on these messages, because TCP, by design, will not do that. But that is not Node core's task, to provide a sort of de facto application messaging protocol (each application protocol -- HTTP, SMTP, etc -- uses its own semantics).

I am sure, however, that there are modules (not just methods like HTTP or WebSockets) that will provide you messaging semantics above TCP. I would suggest looking at one of these.

Assuming I have understood your issue correctly :-), I hope that helps!

**Comment by silverwind** [comment] 2015-05-07 15:09
@ravi great description.

I think UDP might be the right tool for this job, if transmission errors can be handled in the application itself.

**Comment by misterdjules** [comment] 2015-05-07 18:43
Thank you @dayuoba, @silverwind and @ravi. Closing the coalescing of TCP packets as not an issue. The `setNoDelay` call not being effective if the socket is not connected is a duplicate of #8572.

**Closed by misterdjules** 2015-05-07 18:43 UTC

**Comment by dayuoba** [comment] 2015-05-08 04:34
@ravi @silverwind :+1: much thx,learnd a lot
@misterdjules thank you all the same :smile:
