### ISSUE TITLE
stream: readable _read blocking script execution

### ISSUE THREAD

**Issue by trevnorris** [joyent/node#7401] opened 2014-04-02 23:20 UTC
Example script:
```javascript
var Readable = require('stream').Readable;
var util = require('util');

function MyThing() { Readable.call(this); }
util.inherits(MyThing, Readable);

MyThing.prototype._read = function read(size) {
  this.push(new Buffer(10));
  if (this._readableState.buffer.length > 1640)
    throw new Error('buffer is huge!');
};

var thing = new MyThing();

setImmediate(function() {
  thing.on('readable', function() { thing.read(); });
});

setTimeout(function() {
  // Will never be reached.
  process.exit();
});
```

Each execution is pushed onto the `nextTickQueue`. This is a problem and will block the script when processing large amounts of data.

More desired would be to defer after some X number of runs.

**Comment by jasnell** [comment] 2015-05-29 16:17
@trevnorris ... were there any updates on this one?

**Comment by trevnorris** [comment] 2015-06-01 21:51
@jasnell Never came to consensus of how the case should be handled. Only way I know around it would be to force the stream to defer to `setImmediate()` after X calls.

**Comment by jasnell** [comment] 2015-06-25 22:31
Ok, going go out on a limb and say it's not a bug as much as unfortunate side effect of the design. I'm going to close this since there appears to be a workaround but we'll likely want to revisit.

**Closed by jasnell** 2015-06-25 22:31 UTC
Labels: streams
