### ISSUE TITLE
console.log("%%") prints %

### ISSUE THREAD

**Issue by shaharavital** [joyent/node#25917] opened 2015-09-08 19:52 UTC
The console.log function treats any "%%" as "%", so for any sequence of n "%" (n times '%'), only n/2 (or (n+1)/2) of them will be printed.

**Comment by bnoordhuis** [comment] 2015-09-08 19:55
That's the expected and documented (as in 'printf-like') behavior.  Closing, not a bug.

**Closed as completed by bnoordhuis** 2015-09-08 19:55 UTC

**Comment by ChALkeR** [comment] 2015-09-08 20:09
But it doesn't! `console.log('%%')` prints `%%` (when used with a single argument):

```
> console.log('%%')
%%
> console.log('%d%%')
%d%%
```

When used with more than one argument, it behaves like `printf`:

```
> console.log('%%', 3);
% 3
> console.log('%d%%', 3);
3%
```

This is expected and is consistent with how browsers implement it.

**Comment by bnoordhuis** [comment] 2015-09-08 20:12
That's a bug but not what the OP reported.  Please file a separate bug report so things don't get confusing.

**Comment by ChALkeR** [comment] 2015-09-08 20:12
@bnoordhuis That's not a bug.

**Comment by ChALkeR** [comment] 2015-09-08 20:20
Correction: in 0.12 `console.log('%%')` prints `%`, even when used with a single argument.
That is not consistent with browsers.

In 4.0 `console.log('%%')` prints `%%`, when used with a single argument.
That is the expected behavior, though the docs might be made a bit more clear on that one.

Anyway, this discussion does not belong here:

> New issues and pull requests, for all branches, should be opened at [nodejs/node](https://github.com/nodejs/node). 
> New issues and pull requests opened here will automatically be rejected.
