### ISSUE TITLE
Node v0.11.x - NaN values in arrays 

### ISSUE THREAD

**Issue by kgryte** [joyent/node#25743] opened 2015-07-19 20:24 UTC
See the following failing tests: https://travis-ci.org/compute-io/nans/jobs/71677276.

For certain `arrays`, `NaN` values are being converted to 32-bit signed integers, having the minimum 32-signed value: `-2147483648` => `-1 * Math.pow( 2, 31 )`.

The tests do __not__ fail on other Node versions. Is this a bug or some experimental feature?

**Comment by KenanY** [comment] 2015-07-19 22:14
@kgryte Is 0.11 relevant in light of 0.12?

**Comment by kgryte** [comment] 2015-07-20 05:57
@KenanY If 0.11 is purely viewed as `dev` and no longer maintained, no and this issue may be closed.

**Comment by thefourtheye** [comment] 2015-07-20 10:46
@kgryte Can you please provide a sample program to reproduce the problem?

**Comment by kgryte** [comment] 2015-07-20 16:02
This is one of the failing tests...

``` javascript
var assert = require( 'chai' ).assert;

function nans( dims ) {
    return recurse( dims, 0 );
}

function recurse( dims, d ) {
	var out = [],
		len,
		i;

	len = dims[ d ];
	d += 1;
	if ( d < dims.length ) {
		for ( i = 0; i < len; i++ ) {
			out.push( recurse( dims, d ) );
		}
	} else {
		for ( i = 0; i < len; i++ ) {
			out.push( NaN );
		}
	}
	return out;
}

var actual = nans( [100000,2] );
for ( var i = 0; i < actual.length; i++ ) {
	assert.deepEqual( actual[ i ], [NaN,NaN] );
}
```

**Comment by thefourtheye** [comment] 2015-07-21 19:22
True. The problem is reproducible in `v0.11.16`, but not in `v0.12.7`

**Comment by jasnell** [comment] 2015-07-28 18:26
Ok, if the problem is not showing up in v0.12 or v0.10, then closing. v0.11 was dev only.

**Closed by jasnell** 2015-07-28 18:26 UTC
