### ISSUE TITLE
readline with multi-line question (\n) repeats whole question on backspace/delete

### ISSUE THREAD

**Issue by Rob--W** [joyent/node#6415] opened 2013-10-25 21:44 UTC
When a question passed to `readline.question` contains a `\n` character, pressing Enter/Backspace causes the previous questions to be repeated.

Example:

```javascript
var rl = require('readline').createInterface({
    input: process.stdin,
    output: process.stdout
}); 
rl.question('First\nSecond\nThird ', function(answer) {
    rl.close();
    console.log('Result = ' + answer);
});
```

Output:
```
First
Second
Third |
```

After pressing any key, say, "xX"

```
First
Second
Third xX|
```

Now, press backspace to observe the bug:

```
First
Second
First
Second
Third x|
```

As you can see, the last line disappeared, and the whole question is repeated.

Node v0.10.21 on Linux.

**Comment by jasnell** [comment] 2015-05-28 20:08
Unable to reproduce. Closing. Can reopen if necessary

**Closed by jasnell** 2015-05-28 20:08 UTC
Labels: readline
