### ISSUE TITLE
ICU Data customiser does not work with Node

### ISSUE THREAD

**Issue by sxa555** [joyent/node#9246] opened 2015-02-18 18:59 UTC
(This probably needs tagging with intl - FAO @srl295)

The wiki page at https://github.com/joyent/node/wiki/Intl#using-the-small-build suggests that you can use provide additional data at runtime using "a packaged data file /some/path/icudt53l.dat such as from http://apps.icu-project.org/datacustom/"

While I can use the data file that is supplied with the ICU source distribution I cannot get anything from the data customizer tool to work properly - it triggers a memory fault/core dump when I point node at it with the --icu-data-dir parameter and try to use the APIs (for example with the btest402.js mentioned in the wiki)

It's the same failure I get when I point the --icu-data-dir at an empty directory for which there's already an outstanding issue (https://github.com/srl295/node/issues/6 - fixed in upstream V8) - the name file from the customizer tool is identical to the one that comes out of the ICU source distribution (icudt54l.dat) and if I trace the execution it is definitely accessing the correct file, but it just doesn't seem to like it's contents later on:

stat("/dev/shm/dat.icuc/icudt54l.dat", {st_mode=S_IFREG|0644, st_size=28183472, ...}) = 0
open("/dev/shm/dat.icuc/icudt54l.dat", O_RDONLY) = 12
mmap(NULL, 28183472, PROT_READ, MAP_SHARED, 12, 0) = 0x7f2442914000
close(12)                               = 0

**Comment by srl295** [comment] 2015-02-18 19:24
I added a 'may not work' note to the wiki. Also
FYI @misterdjules

**Comment by misterdjules** [comment] 2015-02-18 21:11
@srl295 Thanks for adding the note to the wiki!

**Comment by srl295** [comment] 2015-05-13 17:34
This may be also be caused by [#11672](http://bugs.icu-project.org/trac/ticket/11672)

**Comment by jasnell** [comment] 2015-08-26 18:47
@srl295 ... do we need to keep this one open?

**Comment by jasnell** [comment] 2015-08-29 19:07
Closing this here. Can reopen if necessary.

**Closed by jasnell** 2015-08-29 19:07 UTC
Labels: i18n
