### ISSUE TITLE
illegal access error from decodeURIComponent function.

### ISSUE THREAD

**Issue by lmarkus** [joyent/node#25551] opened 2015-06-20 20:03 UTC
Could you guys take a look at https://github.com/strongloop/express/issues/2652

Might be a bug in the  underlying V8 for Node 0.12.x

**Comment by MichaelHedman** [comment] 2015-06-22 11:36
I am the original reporter of this error, and I agree that the error probably originates from within the V8 code.

This error prevents us from upgrading Node beyond version 0.11.14.

**Comment by jasnell** [comment] 2015-06-24 02:22
@dominic ... there's not a lot to go on here but can you take a look?

**Comment by domenic** [comment] 2015-06-24 02:52
First, of course, is the question of whether this still occurs on a modern V8 version, such as that included in io.js 2.x or io.js next-nightly.

**Comment by lmarkus** [comment] 2015-06-24 05:19
Unfortunately, can't confirm that from my side. We haven't seen this in our dev environments, and can't deploy io.js in prod.

**Comment by lmarkus** [comment] 2015-07-01 16:25
Bump.
Any luck looking into this?
This error continues to surface randomly

**Comment by jasnell** [comment] 2015-07-01 16:38
@lmarkus ... I unfortunately have not had the opportunity to look into it further yet. One thought, however: would you happen to be able to capture the input to the decodeURIComponent that is triggering the error. If the error really is occurring within the decodeURIComponent function in V8, and it's only happening in production, then it's possible that you're getting hit by inputs with invalid code sequences and V8 isn't handling it appropriately. Collecting a log of those inputs ought to allow you to construct a test case that can be used to diagnose the problem.

**Comment by lmarkus** [comment] 2015-07-01 16:53
Fair enough. We'll try to capture that.

**Comment by MichaelHedman** [comment] 2015-07-02 09:25
From what we've seen, when this error occurs ALL strings fail in decodeURIComponent, even empty strings. The problem is that it's really difficult to trigger/reproduce on Heroku (needs a lot of dyno restarts).

@lmarkus can probably reproduce this much easier if he's running in a private environment. Are you running docker btw?

**Comment by lmarkus** [comment] 2015-07-07 14:53
No docker. Plain deploy + PM2

**Comment by jasnell** [comment] 2015-07-10 00:17
Ok, given this it's going to be difficult to diagnose. It's conceivably a problem in the older version of V8 we're using in which case you'd need to test against io.js to see if the issue has been resolved. If a specific issue in V8 can be identified, we can investigate backporting a fix but absent that, there's really not anything we can do here. I'm going to go ahead and close this issue for now, but we can reopen once there is new information and once it's clear that something needs to be fixed in node itself. Fair?

**Closed by jasnell** 2015-07-10 00:17 UTC

**Comment by lmarkus** [comment] 2015-07-10 05:53
That's going to be a tough one.
This is a production deployment at PayPal, so I definitely won't be able to get away with trying io.js.

We will be putting additional logging in place, to see if we can at least come up with a reproducible test case.

Now, if we are able to reproduce, could we realistically expect any action to be taken? (Assuming that this in fact points to V8).

**Comment by jasnell** [comment] 2015-07-10 06:03
Realistically it will depend on just how big of a fix is required.
Backporting patches and floating them in v0.12 or v0.10 is definitely still
possible but will depend entirely on what other changes to v8 are made. We
want this stuff to work so definitely not going to rule it out.

**Comment by dfoody** [comment] 2015-07-13 17:27
We're seeing the same issue in production with 0.12.6 and 0.12.7
It definitely seems to be something related to process startup (it begins failing within 1m of the process starting - but, if the process gets past that point, it doesn't happen).

**Comment by lmarkus** [comment] 2015-07-13 17:42
We've implemented "suicide code" for the time being.
If the error triggers, force restart the process.  This at least gives us some stability while we set up a repro test case.

**Comment by dfoody** [comment] 2015-07-13 23:21
So, a few more points of data about the issue:  Once it happens decodeURIComponent then fails for all subsequent calls.  We added the following code as we detect the issue (right before the process restarts):

**Comment by dfoody** [comment] 2015-07-13 23:25
The other thing we've seen is that it's not always related to process startup.  We've had one case where a process ran for 1hr 12m and handled over 5000 requests before it got into this error state.

**Comment by lmarkus** [comment] 2015-07-14 00:56
Same here. 
A process can have days of uptime, and then it will go sour for all subsequesnt calls.. Hence our suicide code bit. If we detect the error condition, we don't try to contain it anymore, we just restart.

> Notice that the stiffest tree is most easily cracked, while the bamboo or willow survives by bending with the wind.

- Bruce Lee

**Comment by indutny** [comment] 2015-07-14 05:11
I think I can probably fix it. Will need to have a test case to reproduce it, though.

**Comment by MichaelHedman** [comment] 2015-08-03 12:08
Any progress here?

**Comment by dfoody** [comment] 2015-08-03 13:13
We gave up and migrated to io.js (and I can confirm the problem does not occur on io.js).
